### WeRateDogs Twitter Analysis

### Introduction
The purpose of this study is to ingest Twitter data from a variety of sources and formats, assess it for quality and tidyness, clean and analyze the data.  Since the collection of this data was not through a random experiment,  findings are NOT assumed to have causality.

"Data for this project came from the archive of  twitter user @dog_rates archive known as WeRateDogs."  Users send the account pictures of their dogs and they receive a witty response and a rating of the dog.  The rating ranges from 0 to 13 (denominator) and is compared to 10 as the numerator.  WeRateDogs does not follow rigid rating.  They have values above 13.

Twitter provided Udacity permission to use the archive and Twitter also granted this author "Student" access to Tweety (their API) to download the tweet data associated with this project.

Training for techiques used in this analysis came from Udacity Data Analysis class and from pandas and matplotlib documentation at the following URLs:

https://classroom.udacity.com/nanodegrees/nd002/parts/af503f34-9646-4795-a916-190ebc82cb4a

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.extract.html?highlight=str%20extract#pandas.Series.str.extract

https://matplotlib.org/3.1.0/gallery/index.html

https://stackoverflow.com/search?q=save+output+as+.png+matplotlib

Information on WeRate dogs also obatined from Wikipedia at the following link:  https://en.wikipedia.org/wiki/WeRateDogs

In [1]:
# import modules needed to work with this dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import requests

In [2]:
# read the twitter-archive-enhanced csv file into a data frame called twitter_archive_enhanced
twitter_archive_enhanced = pd.read_csv('twitter-archive-enhanced.csv')

In [3]:
# create a copy of twitter_archive_enhanced to be used with the tweepy API
tw1 = twitter_archive_enhanced

In [4]:
# The code to perform this step was provided by Udacity at the following link: 
# https://video.udacity-data.com/topher/2018/November/5be5fb4c_twitter-api/twitter-api.py

# this imports the tweepy application to be used by pandas
import tweepy
# this is the authorization module required by Twitter
from tweepy import OAuthHandler
# this allows the reading of json files
import json
# thi creates a timer as Twitter limits the amount of data that can be pulled within a timeframe
from timeit import default_timer as timer
# 
# These are hidden to comply with Twitter's API terms and conditions
consumer_key = 'HIDDEN'
consumer_secret = 'HIDDEN'
access_token = 'HIDDEN'
access_secret = 'HIDDEN'

auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth, wait_on_rate_limit=True)

# this establishes the list of tweet ids, taken from twitter-archive-enhanced.csv that will be compared to 
# the twitter json data on the Tweepy platform.
tweet_ids = tw1.tweet_id.values
len(tweet_ids)

# Query Twitter's API for JSON data for each tweet ID in the Twitter archive
count = 0
fails_dict = {}
start = timer()
# Save each tweet's returned JSON as a new line in a .txt file and writes it out as tweet_json.txt
with open('tweet_json.txt', 'w') as outfile:
    # This loop will likely take 20-30 minutes to run because of Twitter's rate limit
    for tweet_id in tweet_ids:
        count += 1
        print(str(count) + ": " + str(tweet_id))
        try:
            tweet = api.get_status(tweet_id, tweet_mode='extended')
            print("Success")
            json.dump(tweet._json, outfile)
            outfile.write('\n')
        except tweepy.TweepError as e:
            print("Fail")
            fails_dict[tweet_id] = e
            pass
end = timer()
print(end - start)
print(fails_dict)

1: 892420643555336193
Success
2: 892177421306343426
Success
3: 891815181378084864
Success
4: 891689557279858688
Success
5: 891327558926688256
Success
6: 891087950875897856
Success
7: 890971913173991426
Success
8: 890729181411237888
Success
9: 890609185150312448
Success
10: 890240255349198849
Success
11: 890006608113172480
Success
12: 889880896479866881
Success
13: 889665388333682689
Success
14: 889638837579907072
Success
15: 889531135344209921
Success
16: 889278841981685760
Success
17: 888917238123831296
Success
18: 888804989199671297
Success
19: 888554962724278272
Success
20: 888202515573088257
Fail
21: 888078434458587136
Success
22: 887705289381826560
Success
23: 887517139158093824
Success
24: 887473957103951883
Success
25: 887343217045368832
Success
26: 887101392804085760
Success
27: 886983233522544640
Success
28: 886736880519319552
Success
29: 886680336477933568
Success
30: 886366144734445568
Success
31: 886267009285017600
Success
32: 886258384151887873
Success
33: 8860541600590725

Fail
262: 842846295480000512
Success
263: 842765311967449089
Success
264: 842535590457499648
Success
265: 842163532590374912
Success
266: 842115215311396866
Success
267: 841833993020538882
Success
268: 841680585030541313
Success
269: 841439858740625411
Success
270: 841320156043304961
Success
271: 841314665196081154
Success
272: 841077006473256960
Success
273: 840761248237133825
Success
274: 840728873075638272
Success
275: 840698636975636481
Success
276: 840696689258311684
Success
277: 840632337062862849
Success
278: 840370681858686976
Success
279: 840268004936019968
Success
280: 839990271299457024
Success
281: 839549326359670784
Success
282: 839290600511926273
Success
283: 839239871831150596
Success
284: 838952994649550848
Success
285: 838921590096166913
Success
286: 838916489579200512
Success
287: 838831947270979586
Success
288: 838561493054533637
Success
289: 838476387338051585
Success
290: 838201503651401729
Success
291: 838150277551247360
Success
292: 838085839343206401
Success
293

Success
519: 810657578271330305
Success
520: 810284430598270976
Success
521: 810254108431155201
Success
522: 809920764300447744
Success
523: 809808892968534016
Success
524: 809448704142938112
Success
525: 809220051211603969
Success
526: 809084759137812480
Success
527: 808838249661788160
Success
528: 808733504066486276
Success
529: 808501579447930884
Success
530: 808344865868283904
Success
531: 808134635716833280
Success
532: 808106460588765185
Success
533: 808001312164028416
Success
534: 807621403335917568
Success
535: 807106840509214720
Success
536: 807059379405148160
Success
537: 807010152071229440
Success
538: 806629075125202948
Success
539: 806620845233815552
Success
540: 806576416489959424
Success
541: 806542213899489280
Success
542: 806242860592926720
Success
543: 806219024703037440
Success
544: 805958939288408065
Success
545: 805932879469572096
Success
546: 805826884734976000
Success
547: 805823200554876929
Success
548: 805520635690676224
Success
549: 805487436403003392
Success


Success
776: 776201521193218049
Success
777: 776113305656188928
Success
778: 776088319444877312
Success
779: 775898661951791106
Success
780: 775842724423557120
Success
781: 775733305207554048
Success
782: 775729183532220416
Success
783: 775364825476165632
Success
784: 775350846108426240
Success
785: 775096608509886464
Fail
786: 775085132600442880
Success
787: 774757898236878852
Success
788: 774639387460112384
Success
789: 774314403806253056
Success
790: 773985732834758656
Success
791: 773922284943896577
Success
792: 773704687002451968
Success
793: 773670353721753600
Success
794: 773547596996571136
Success
795: 773336787167145985
Success
796: 773308824254029826
Success
797: 773247561583001600
Success
798: 773191612633579521
Success
799: 772877495989305348
Success
800: 772826264096874500
Success
801: 772615324260794368
Success
802: 772581559778025472
Success
803: 772193107915964416
Success
804: 772152991789019136
Success
805: 772117678702071809
Success
806: 772114945936949249
Success
807

Success
1032: 745422732645535745
Success
1033: 745314880350101504
Success
1034: 745074613265149952
Success
1035: 745057283344719872
Success
1036: 744995568523612160
Success
1037: 744971049620602880
Success
1038: 744709971296780288
Success
1039: 744334592493166593
Success
1040: 744234799360020481
Success
1041: 744223424764059648
Success
1042: 743980027717509120
Success
1043: 743895849529389061
Success
1044: 743835915802583040
Success
1045: 743609206067040256
Success
1046: 743595368194129920
Success
1047: 743545585370791937
Success
1048: 743510151680958465
Success
1049: 743253157753532416
Success
1050: 743222593470234624
Success
1051: 743210557239623680
Success
1052: 742534281772302336
Success
1053: 742528092657332225
Success
1054: 742465774154047488
Success
1055: 742423170473463808
Success
1056: 742385895052087300
Success
1057: 742161199639494656
Success
1058: 742150209887731712
Success
1059: 741793263812808706
Success
1060: 741743634094141440
Success
1061: 741438259667034112
Success
10

Success
1281: 708834316713893888
Success
1282: 708810915978854401
Success
1283: 708738143638450176
Success
1284: 708711088997666817
Success
1285: 708479650088034305
Success
1286: 708469915515297792
Success
1287: 708400866336894977
Success
1288: 708356463048204288
Success
1289: 708349470027751425
Success
1290: 708149363256774660
Success
1291: 708130923141795840
Success
1292: 708119489313951744
Success
1293: 708109389455101952
Success
1294: 708026248782585858
Success
1295: 707995814724026368
Success
1296: 707983188426153984
Success
1297: 707969809498152960
Success
1298: 707776935007539200
Success
1299: 707741517457260545
Success
1300: 707738799544082433
Success
1301: 707693576495472641
Success
1302: 707629649552134146
Success
1303: 707610948723478529
Success
1304: 707420581654872064
Success
1305: 707411934438625280
Success
1306: 707387676719185920
Success
1307: 707377100785885184
Success
1308: 707315916783140866
Success
1309: 707297311098011648
Success
1310: 707059547140169728
Success
13

Success
1530: 690248561355657216
Success
1531: 690021994562220032
Success
1532: 690015576308211712
Success
1533: 690005060500217858
Success
1534: 689999384604450816
Success
1535: 689993469801164801
Success
1536: 689977555533848577
Success
1537: 689905486972461056
Success
1538: 689877686181715968
Success
1539: 689835978131935233
Success
1540: 689661964914655233
Success
1541: 689659372465688576
Success
1542: 689623661272240129
Success
1543: 689599056876867584
Success
1544: 689557536375177216
Success
1545: 689517482558820352
Success
1546: 689289219123089408
Success
1547: 689283819090870273
Success
1548: 689280876073582592
Success
1549: 689275259254616065
Success
1550: 689255633275777024
Success
1551: 689154315265683456
Success
1552: 689143371370250240
Success
1553: 688916208532455424
Success
1554: 688908934925697024
Success
1555: 688898160958271489
Success
1556: 688894073864884227
Success
1557: 688828561667567616
Success
1558: 688804835492233216
Success
1559: 688789766343622656
Success
15

Success
1779: 677895101218201600
Success
1780: 677716515794329600
Success
1781: 677700003327029250
Success
1782: 677698403548192770
Success
1783: 677687604918272002
Success
1784: 677673981332312066
Success
1785: 677662372920729601
Success
1786: 677644091929329666
Success
1787: 677573743309385728
Success
1788: 677565715327688705
Success
1789: 677557565589463040
Success
1790: 677547928504967168
Success
1791: 677530072887205888
Success
1792: 677335745548390400
Success
1793: 677334615166730240
Success
1794: 677331501395156992
Success
1795: 677328882937298944
Success
1796: 677314812125323265
Success
1797: 677301033169788928
Success
1798: 677269281705472000
Success
1799: 677228873407442944
Success
1800: 677187300187611136
Success
1801: 676975532580409345
Success
1802: 676957860086095872
Success
1803: 676949632774234114
Success
1804: 676948236477857792
Success
1805: 676946864479084545
Success
1806: 676942428000112642
Success
1807: 676936541936185344
Success
1808: 676916996760600576
Success
18

Success
2028: 671874878652489728
Success
2029: 671866342182637568
Success
2030: 671855973984772097
Success
2031: 671789708968640512
Success
2032: 671768281401958400
Success
2033: 671763349865160704
Success
2034: 671744970634719232
Success
2035: 671743150407421952
Success
2036: 671735591348891648
Success
2037: 671729906628341761
Success
2038: 671561002136281088
Success
2039: 671550332464455680
Success
2040: 671547767500775424
Success
2041: 671544874165002241
Success
2042: 671542985629241344
Success
2043: 671538301157904385
Success
2044: 671536543010570240
Success
2045: 671533943490011136
Success
2046: 671528761649688577
Success
2047: 671520732782923777
Success
2048: 671518598289059840
Success
2049: 671511350426865664
Success
2050: 671504605491109889
Success
2051: 671497587707535361
Success
2052: 671488513339211776
Success
2053: 671486386088865792
Success
2054: 671485057807351808
Success
2055: 671390180817915904
Success
2056: 671362598324076544
Success
2057: 671357843010908160
Success
20

Success
2277: 667443425659232256
Success
2278: 667437278097252352
Success
2279: 667435689202614272
Success
2280: 667405339315146752
Success
2281: 667393430834667520
Success
2282: 667369227918143488
Success
2283: 667211855547486208
Success
2284: 667200525029539841
Success
2285: 667192066997374976
Success
2286: 667188689915760640
Success
2287: 667182792070062081
Success
2288: 667177989038297088
Success
2289: 667176164155375616
Success
2290: 667174963120574464
Success
2291: 667171260800061440
Success
2292: 667165590075940865
Success
2293: 667160273090932737
Success
2294: 667152164079423490
Success
2295: 667138269671505920
Success
2296: 667119796878725120
Success
2297: 667090893657276420
Success
2298: 667073648344346624
Success
2299: 667070482143944705
Success
2300: 667065535570550784
Success
2301: 667062181243039745
Success
2302: 667044094246576128
Success
2303: 667012601033924608
Success
2304: 666996132027977728
Success
2305: 666983947667116034
Success
2306: 666837028449972224
Success
23

Received the following error message for 24 tweets that failed (in the list above)

###  Error Messages

{888202515573088257: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 873697596434513921: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 872668790621863937: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 872261713294495745: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 869988702071779329: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 866816280283807744: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 861769973181624320: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 856602993587888130: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 851953902622658560: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 845459076796616705: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 844704788403113984: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 842892208864923648: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 837366284874571778: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 837012587749474308: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 829374341691346946: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 827228250799742977: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 812747805718642688: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 802247111496568832: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 779123168116150273: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 775096608509886464: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 771004394259247104: TweepError([{'code': 179, 'message': 'Sorry, you are not authorized to see this status.'}]), 770743923962707968: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 759566828574212096: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 754011816964026368: TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), 680055455951884288: TweepError([{'code': 144, 'message': 'No status found with that ID.'}])}  


After further analysis, this appears to primarily be due to the timer.  Since we are using the tweets from the json file, not having these will not impede the analysis





This step adds borders to the output (to improve viewability).  The code/technique to do this was obtained on Stack Exchange: https://stackoverflow.com/questions/48798508/jupyter-pandas-dataframe-output-table-format-configuration

In [7]:
%%HTML
<style type="text/css">
    table.dataframe td, table.dataframe th {
        border-style: solid;
    }
</style>

This step reads in the tweet_json file obtained by querying the Tweety API.

In [8]:
# extract dat from the tweet_json.txt file obtained from the Tweepy API
with open('tweet_json.txt', 'rb') as f:
    tweets=pd.read_json(f,lines=True, encoding = 'utf-8') 


In [9]:
# displays tweet data contents
tweets.head()

created_at                  id              id_str  \
0 2017-08-01 16:23:56+00:00  892420643555336193  892420643555336192   
1 2017-08-01 00:17:27+00:00  892177421306343426  892177421306343424   
2 2017-07-31 00:18:03+00:00  891815181378084864  891815181378084864   
3 2017-07-30 15:58:51+00:00  891689557279858688  891689557279858688   
4 2017-07-29 16:00:24+00:00  891327558926688256  891327558926688256   

                                           full_text  truncated  \
0  This is Phineas. He's a mystical boy. Only eve...      False   
1  This is Tilly. She's just checking pup on you....      False   
2  This is Archie. He is a rare Norwegian Pouncin...      False   
3  This is Darla. She commenced a snooze mid meal...      False   
4  This is Franklin. He would like you to stop ca...      False   

  display_text_range                                           entities  \
0            [0, 85]  {'hashtags': [], 'symbols': [], 'user_mentions...   
1           [0, 138]  {'hashtags': [], 'symbols': [], 'user_mentions...   
2           [0, 121]  {'hashtags': [], 'symbols': [], 'user_mentions...   
3            [0, 79]  {'hashtags': [], 'symbols': [], 'user_mentions...   
4           [0, 138]  {'hashtags': [{'text': 'BarkWeek', 'indices': ...   

                                   extended_entities  \
0  {'media': [{'id': 892420639486877696, 'id_str'...   
1  {'media': [{'id': 892177413194625024, 'id_str'...   
2  {'media': [{'id': 891815175371796480, 'id_str'...   
3  {'media': [{'id': 891689552724799489, 'id_str'...   
4  {'media': [{'id': 891327551943041024, 'id_str'...   

                                              source  in_reply_to_status_id  \
0  <a href="http://twitter.com/download/iphone" r...                    NaN   
1  <a href="http://twitter.com/download/iphone" r...                    NaN   
2  <a href="http://twitter.com/download/iphone" r...                    NaN   
3  <a href="http://twitter.com/download/iphone" r...                    NaN   
4  <a href="http://twitter.com/download/iphone" r...                    NaN   

   ...  favorited  retweeted  possibly_sensitive  \
0  ...      False      False                 0.0   
1  ...      False      False                 0.0   
2  ...      False      False                 0.0   
3  ...      False      False                 0.0   
4  ...      False      False                 0.0   

  possibly_sensitive_appealable lang  retweeted_status  quoted_status_id  \
0                           0.0   en               NaN               NaN   
1                           0.0   en               NaN               NaN   
2                           0.0   en               NaN               NaN   
3                           0.0   en               NaN               NaN   
4                           0.0   en               NaN               NaN   

  quoted_status_id_str  quoted_status_permalink  quoted_status  
0                  NaN                      NaN            NaN  
1                  NaN                      NaN            NaN  
2                  NaN                      NaN            NaN  
3                  NaN                      NaN            NaN  
4                  NaN                      NaN            NaN  

[5 rows x 32 columns]

Next, let's load the Twitter image predictions

In [10]:
# this code downloads the image predictions from the internet location
response = requests.get('https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv')
with open('image_predictions.tsv', 'wb') as file:
    file.write(response.content)

In [11]:
# read in the image_prediction.csv file
image_predictions = pd.read_csv('image_predictions.tsv', sep = '\t')
image_predictions.head()

tweet_id                                          jpg_url  \
0  666020888022790149  https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg   
1  666029285002620928  https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg   
2  666033412701032449  https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg   
3  666044226329800704  https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg   
4  666049248165822465  https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg   

   img_num                      p1   p1_conf  p1_dog                  p2  \
0        1  Welsh_springer_spaniel  0.465074    True              collie   
1        1                 redbone  0.506826    True  miniature_pinscher   
2        1         German_shepherd  0.596461    True            malinois   
3        1     Rhodesian_ridgeback  0.408143    True             redbone   
4        1      miniature_pinscher  0.560311    True          Rottweiler   

    p2_conf  p2_dog                   p3   p3_conf  p3_dog  
0  0.156665    True    Shetland_sheepdog  0.061428    True  
1  0.074192    True  Rhodesian_ridgeback  0.072010    True  
2  0.138584    True           bloodhound  0.116197    True  
3  0.360687    True   miniature_pinscher  0.222752    True  
4  0.243682    True             Doberman  0.154629    True

The data wrangling starts by understanding what data is contained in each of the files.  Let's start with twitter_archive_enhanced

In [12]:
# displays twitter contents
twitter_archive_enhanced.head()

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
0  892420643555336193                    NaN                  NaN   
1  892177421306343426                    NaN                  NaN   
2  891815181378084864                    NaN                  NaN   
3  891689557279858688                    NaN                  NaN   
4  891327558926688256                    NaN                  NaN   

                   timestamp  \
0  2017-08-01 16:23:56 +0000   
1  2017-08-01 00:17:27 +0000   
2  2017-07-31 00:18:03 +0000   
3  2017-07-30 15:58:51 +0000   
4  2017-07-29 16:00:24 +0000   

                                              source  \
0  <a href="http://twitter.com/download/iphone" r...   
1  <a href="http://twitter.com/download/iphone" r...   
2  <a href="http://twitter.com/download/iphone" r...   
3  <a href="http://twitter.com/download/iphone" r...   
4  <a href="http://twitter.com/download/iphone" r...   

                                                text  retweeted_status_id  \
0  This is Phineas. He's a mystical boy. Only eve...                  NaN   
1  This is Tilly. She's just checking pup on you....                  NaN   
2  This is Archie. He is a rare Norwegian Pouncin...                  NaN   
3  This is Darla. She commenced a snooze mid meal...                  NaN   
4  This is Franklin. He would like you to stop ca...                  NaN   

   retweeted_status_user_id retweeted_status_timestamp  \
0                       NaN                        NaN   
1                       NaN                        NaN   
2                       NaN                        NaN   
3                       NaN                        NaN   
4                       NaN                        NaN   

                                       expanded_urls  rating_numerator  \
0  https://twitter.com/dog_rates/status/892420643...                13   
1  https://twitter.com/dog_rates/status/892177421...                13   
2  https://twitter.com/dog_rates/status/891815181...                12   
3  https://twitter.com/dog_rates/status/891689557...                13   
4  https://twitter.com/dog_rates/status/891327558...                12   

   rating_denominator      name doggo floofer pupper puppo  
0                  10   Phineas  None    None   None  None  
1                  10     Tilly  None    None   None  None  
2                  10    Archie  None    None   None  None  
3                  10     Darla  None    None   None  None  
4                  10  Franklin  None    None   None  None

We will dig into the file, starting with the "names" variable

In [13]:
# display the content of name field
tw_names = twitter_archive_enhanced.name.value_counts()
tw_names

None        745
a            55
Charlie      12
Oliver       11
Cooper       11
           ... 
Laela         1
Clyde         1
Julius        1
Berkeley      1
Ralph         1
Name: name, Length: 957, dtype: int64

At first glance, we see there are 745 values of "None". In addition, there are some non-name words in the file like "a", "the", and "an".   

We need to further investigate the data where name = None

In [14]:
# identifies names equal to none
twitter_archive_enhanced[twitter_archive_enhanced['name'] == "None"]


tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
5     891087950875897856                    NaN                  NaN   
7     890729181411237888                    NaN                  NaN   
12    889665388333682689                    NaN                  NaN   
24    887343217045368832                    NaN                  NaN   
25    887101392804085760                    NaN                  NaN   
...                  ...                    ...                  ...   
2342  666082916733198337                    NaN                  NaN   
2343  666073100786774016                    NaN                  NaN   
2344  666071193221509120                    NaN                  NaN   
2351  666049248165822465                    NaN                  NaN   
2355  666020888022790149                    NaN                  NaN   

                      timestamp  \
5     2017-07-29 00:08:17 +0000   
7     2017-07-28 00:22:40 +0000   
12    2017-07-25 01:55:32 +0000   
24    2017-07-18 16:08:03 +0000   
25    2017-07-18 00:07:08 +0000   
...                         ...   
2342  2015-11-16 02:38:37 +0000   
2343  2015-11-16 01:59:36 +0000   
2344  2015-11-16 01:52:02 +0000   
2351  2015-11-16 00:24:50 +0000   
2355  2015-11-15 22:32:08 +0000   

                                                 source  \
5     <a href="http://twitter.com/download/iphone" r...   
7     <a href="http://twitter.com/download/iphone" r...   
12    <a href="http://twitter.com/download/iphone" r...   
24    <a href="http://twitter.com/download/iphone" r...   
25    <a href="http://twitter.com/download/iphone" r...   
...                                                 ...   
2342  <a href="http://twitter.com/download/iphone" r...   
2343  <a href="http://twitter.com/download/iphone" r...   
2344  <a href="http://twitter.com/download/iphone" r...   
2351  <a href="http://twitter.com/download/iphone" r...   
2355  <a href="http://twitter.com/download/iphone" r...   

                                                   text  retweeted_status_id  \
5     Here we have a majestic great white breaching ...                  NaN   
7     When you watch your owner call another dog a g...                  NaN   
12    Here's a puppo that seems to be on the fence a...                  NaN   
24    You may not have known you needed to see this ...                  NaN   
25    This... is a Jubilant Antarctic House Bear. We...                  NaN   
...                                                 ...                  ...   
2342  Here we have a well-established sunblockerspan...                  NaN   
2343  Let's hope this flight isn't Malaysian (lol). ...                  NaN   
2344  Here we have a northern speckled Rhododendron....                  NaN   
2351  Here we have a 1949 1st generation vulpix. Enj...                  NaN   
2355  Here we have a Japanese Irish Setter. Lost eye...                  NaN   

      retweeted_status_user_id retweeted_status_timestamp  \
5                          NaN                        NaN   
7                          NaN                        NaN   
12                         NaN                        NaN   
24                         NaN                        NaN   
25                         NaN                        NaN   
...                        ...                        ...   
2342                       NaN                        NaN   
2343                       NaN                        NaN   
2344                       NaN                        NaN   
2351                       NaN                        NaN   
2355                       NaN                        NaN   

                                          expanded_urls  rating_numerator  \
5     https://twitter.com/dog_rates/status/891087950...                13   
7     https://twitter.com/dog_rates/status/890729181...                13   
12    https://twitter.com/dog_rates/status/889665388...                13   
24    https://twitt

Looking through the text variable where name is equal to None in the table above, some names do appear.  We will need to add those names.

Setting the maximum rows displayed to 1000 in order to see all of the names in order to make a list of names to delete.

In [15]:
# changes system option for display to 1000 rows
pd.set_option('display.max_rows', 1000)
# displays names and number of names
twitter_archive_enhanced['name'].value_counts()

None              745
a                  55
Charlie            12
Oliver             11
Cooper             11
Lucy               11
Lola               10
Tucker             10
Penny              10
Bo                  9
Winston             9
Sadie               8
the                 8
Daisy               7
an                  7
Bailey              7
Toby                7
Buddy               7
Dave                6
Oscar               6
Jack                6
Jax                 6
Leo                 6
Scout               6
Bella               6
Milo                6
Stanley             6
Koda                6
Rusty               6
Bentley             5
Sammy               5
Alfie               5
Sunny               5
Finn                5
Larry               5
George              5
Oakley              5
Phil                5
Gus                 5
Chester             5
very                5
Louis               5
Sophie              4
quite               4
Brody               4
just      

There are 745 rows where name = None.  We need to see if they can be found in the text field.

In [16]:
# display the retweeted_status_id field contents
twitter_archive_enhanced['retweeted_status_id'].value_counts()

7.757333e+17    1
7.507196e+17    1
6.742918e+17    1
6.833919e+17    1
8.269587e+17    1
8.780576e+17    1
7.320056e+17    1
7.186315e+17    1
6.732953e+17    1
7.914070e+17    1
8.447048e+17    1
7.862340e+17    1
8.685523e+17    1
7.504293e+17    1
8.327664e+17    1
6.690004e+17    1
6.873173e+17    1
7.638376e+17    1
7.815247e+17    1
8.092201e+17    1
8.000650e+17    1
8.174239e+17    1
8.001414e+17    1
7.909461e+17    1
7.867091e+17    1
8.406323e+17    1
8.688804e+17    1
7.869631e+17    1
7.733088e+17    1
8.222448e+17    1
7.599238e+17    1
7.776842e+17    1
7.410673e+17    1
8.316501e+17    1
7.012147e+17    1
7.950767e+17    1
8.178278e+17    1
7.363926e+17    1
6.733201e+17    1
8.768508e+17    1
8.011679e+17    1
7.823059e+17    1
6.914169e+17    1
8.630625e+17    1
8.224891e+17    1
7.827226e+17    1
8.860537e+17    1
6.798284e+17    1
8.008540e+17    1
8.370113e+17    1
6.791584e+17    1
6.753544e+17    1
7.467577e+17    1
6.790626e+17    1
8.591970e+17    1
7.790561e+

Next, we need to remove any tweet records that were retweets.  The retweeted_status_id should provide a guide to removal of the records.

Furthering the understanding of the variables, we will look at the doggo, puppo, pupper, and floofer fields to see how it is populated.

In [17]:
# displays the contents of doggo
twitter_archive_enhanced['doggo'].value_counts()

None     2259
doggo      97
Name: doggo, dtype: int64

In [18]:
# displays the contents of puppo
twitter_archive_enhanced['puppo'].value_counts()

None     2326
puppo      30
Name: puppo, dtype: int64

In [19]:
# displays the contents of pupper
twitter_archive_enhanced['pupper'].value_counts()

None      2099
pupper     257
Name: pupper, dtype: int64

In [20]:
# displays the contents of floofer
twitter_archive_enhanced['floofer'].value_counts()

None       2346
floofer      10
Name: floofer, dtype: int64

We can see that doggo has the value of doggo if the animal is identified in that stage, otherwise it is populated with None.  This is a tidy data issue.  doggo, puppo, pupper, and floofer should be moved under a single variable, called development_stage.  This eliminates additional variables.

We now turn to the rating numerator and denominator.

In [21]:
# displays the contents of rating_numerator
twitter_archive_enhanced['rating_numerator'].value_counts()

12      558
11      464
10      461
13      351
9       158
8       102
7        55
14       54
5        37
6        32
3        19
4        17
1         9
2         9
420       2
0         2
15        2
75        2
80        1
20        1
24        1
26        1
44        1
50        1
60        1
165       1
84        1
88        1
144       1
182       1
143       1
666       1
960       1
1776      1
17        1
27        1
45        1
99        1
121       1
204       1
Name: rating_numerator, dtype: int64

Looking at the rating numerator, we see values as high as 1776.  The WeRateDogs Wikipedia page indicated the ratings numerator is is up to 13, however, the rating structure is not followed rigidly and is considered one of the things appealing to followers.  In this study, the high rating records were not removed and the analysis will not utilize the rating information.

In [22]:
# displays the contents of rating_denominator
twitter_archive_enhanced['rating_denominator'].value_counts()

10     2333
11        3
50        3
80        2
20        2
2         1
16        1
40        1
70        1
15        1
90        1
110       1
120       1
130       1
150       1
170       1
7         1
0         1
Name: rating_denominator, dtype: int64

Looking at the rating denominator, we see values ranging from 170 to 0.  As the ratings are quirky and will not be used in the study, the records in excess of 13 will not be removed.

In [23]:
# displays the minimum information of the twitter_enhanced_arhive dataset
twitter_archive_enhanced.min()

tweet_id                                                   666020888022790149
in_reply_to_status_id                                             6.65815e+17
in_reply_to_user_id                                               1.18563e+07
timestamp                                           2015-11-15 22:32:08 +0000
source                      <a href="http://twitter.com" rel="nofollow">Tw...
text                        "AND IIIIIIIIIIIEIIIIIIIIIIIII WILL ALWAYS LOV...
retweeted_status_id                                               6.66104e+17
retweeted_status_user_id                                               783214
rating_numerator                                                            0
rating_denominator                                                          0
name                                                                     Abby
doggo                                                                    None
floofer                                                         

Looking at the min values of the twitter_archive_enhanced dataset, we see that the text contains the Twitter URL.  This should be put in a separate column (Tidyness issue).

In [24]:
# displays the maximum information of the twitter_enhanced_arhive dataset
twitter_archive_enhanced.max()

tweet_id                                                   892420643555336193
in_reply_to_status_id                                             8.86266e+17
in_reply_to_user_id                                               8.40548e+17
timestamp                                           2017-08-01 16:23:56 +0000
source                      <a href="https://about.twitter.com/products/tw...
text                        😂😂😂 10/10 for the dog and the owner https://t....
retweeted_status_id                                               8.87474e+17
retweeted_status_user_id                                          7.87462e+17
rating_numerator                                                         1776
rating_denominator                                                        170
name                                                                     very
doggo                                                                   doggo
floofer                                                         

Now, let's understand the structure of the data using .info()

In [25]:
# displays the file types for each field
twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   tweet_id                    2356 non-null   int64  
 1   in_reply_to_status_id       78 non-null     float64
 2   in_reply_to_user_id         78 non-null     float64
 3   timestamp                   2356 non-null   object 
 4   source                      2356 non-null   object 
 5   text                        2356 non-null   object 
 6   retweeted_status_id         181 non-null    float64
 7   retweeted_status_user_id    181 non-null    float64
 8   retweeted_status_timestamp  181 non-null    object 
 9   expanded_urls               2297 non-null   object 
 10  rating_numerator            2356 non-null   int64  
 11  rating_denominator          2356 non-null   int64  
 12  name                        2356 non-null   object 
 13  doggo                       2356 

The following issues are visible in from the result above:
* tweet ID should be an integer64, not a float
* in_reply_to_status_id and in_reply_to_user_id should be an integer64, not float
* timestamp should be datetime, no object
* there appear to be 181 retweeted items based on retweeted_status_id, retweeted_status_user_id, and retweeted_status_timestamp
* retweeted status timestamp should be datetime, not object

Checking to see if retweeted_status_timestamp has values populated as this dield has the potential to be used to remove retweets.

In [26]:
# displays the contents of the retweeted_status field
twitter_archive_enhanced['retweeted_status_timestamp'].value_counts()

2016-07-12 18:27:35 +0000    1
2017-01-13 17:00:21 +0000    1
2016-12-17 00:38:52 +0000    1
2017-03-04 00:21:08 +0000    1
2016-07-06 15:54:42 +0000    1
2017-04-24 02:13:14 +0000    1
2016-12-15 02:14:29 +0000    1
2017-02-24 23:04:14 +0000    1
2015-11-20 01:06:48 +0000    1
2015-12-12 02:23:01 +0000    1
2016-08-15 16:22:20 +0000    1
2017-01-11 02:21:57 +0000    1
2016-09-25 00:06:08 +0000    1
2016-01-08 05:00:14 +0000    1
2017-04-20 18:14:33 +0000    1
2016-09-14 17:40:06 +0000    1
2017-01-07 20:18:46 +0000    1
2016-09-09 18:31:54 +0000    1
2016-10-03 15:42:44 +0000    1
2017-07-15 02:44:07 +0000    1
2016-10-02 23:23:04 +0000    1
2016-10-13 23:23:56 +0000    1
2016-08-05 21:19:27 +0000    1
2016-08-28 16:51:16 +0000    1
2016-02-02 23:52:22 +0000    1
2016-10-08 18:41:19 +0000    1
2017-01-15 21:49:15 +0000    1
2017-03-01 18:47:10 +0000    1
2016-10-12 15:55:59 +0000    1
2016-11-22 00:10:52 +0000    1
2016-03-09 16:56:11 +0000    1
2016-08-31 15:10:07 +0000    1
2016-09-

In [27]:
# displays the contents of the retweeted_status_user_id field
twitter_archive_enhanced['retweeted_status_user_id'].min()

783214.0

retweeted_status_user_id can also be used to remove the retweets.

In [28]:
# looks for a way to identify retweeted rows of data in twitter_archive_enhanced
twitter_archive_enhanced.query('in_reply_to_status_id > 0')

tweet_id  in_reply_to_status_id  in_reply_to_user_id  \
30    886267009285017600           8.862664e+17         2.281182e+09   
55    881633300179243008           8.816070e+17         4.738443e+07   
64    879674319642796034           8.795538e+17         3.105441e+09   
113   870726314365509632           8.707262e+17         1.648776e+07   
148   863427515083354112           8.634256e+17         7.759620e+07   
149   863079547188785154           6.671522e+17         4.196984e+09   
179   857214891891077121           8.571567e+17         1.806710e+08   
184   856526610513747968           8.558181e+17         4.196984e+09   
186   856288084350160898           8.562860e+17         2.792810e+08   
188   855862651834028034           8.558616e+17         1.943518e+08   
189   855860136149123072           8.558585e+17         1.361572e+07   
218   850333567704068097           8.503288e+17         2.195506e+07   
228   848213670039564288           8.482121e+17         4.196984e+09   
234   847617282490613760           8.476062e+17         4.196984e+09   
251   844979544864018432           7.590995e+17         4.196984e+09   
274   840698636975636481           8.406983e+17         8.405479e+17   
290   838150277551247360           8.381455e+17         2.195506e+07   
291   838085839343206401           8.380855e+17         2.894131e+09   
313   835246439529840640           8.352460e+17         2.625958e+07   
342   832088576586297345           8.320875e+17         3.058208e+07   
346   831926988323639298           8.319030e+17         2.068372e+07   
387   826598799820865537           8.265984e+17         4.196984e+09   
409   823333489516937216           8.233264e+17         1.582854e+09   
427   821153421864615936           8.211526e+17         1.132119e+08   
498   813130366689148928           8.131273e+17         4.196984e+09   
513   811647686436880384           8.116272e+17         4.196984e+09   
565   802265048156610565           7.331095e+17         4.196984e+09   
570   801854953262350336           8.018543e+17         1.185634e+07   
576   800859414831898624           8.008580e+17         2.918590e+08   
611   797165961484890113           7.971238e+17         2.916630e+07   
701   786051337297522688           7.727430e+17         7.305050e+17   
843   766714921925144576           7.667118e+17         4.196984e+09   
857   763956972077010945           7.638652e+17         1.584641e+07   
967   750381685133418496           7.501805e+17         4.717297e+09   
1005  747651430853525504           7.476487e+17         4.196984e+09   
1016  746906459439529985           7.468859e+17         4.196984e+09   
1018  746818907684614144           6.914169e+17         4.196984e+09   
1080  738891149612572673           7.384119e+17         3.589728e+08   
1127  729838605770891264           7.291135e+17         4.196984e+09   
1295  707983188426153984           7.079801e+17         2.319108e+09   
1330  705786532653883392           7.032559e+17         4.196984e+09   
1339  704871453724954624           6.671522e+17         4.196984e+09   
1345  704491224099647488           7.044857e+17         2.878549e+07   
1356  703425003149250560           7.030419e+17         4.196984e+09   
1446  696490539101908992           6.964887e+17         4.196984e+09   
1452  695767669421768709           6.753494e+17         4.196984e+09   
1464  694356675654983680           6.706684e+17         4.196984e+09   
1474  693644216740769793           6.936422e+17         4.196984e+09   
1479  693582294167244802           6.935722e+17         1.198989e+09   
1497  692423280028966913           6.924173e+17         4.196984e+09   
1501  692142790915014657           6.920419e+17         4.196984e+09   
1523  690607260360429569           6.903413e+17         4.670367e+08   
1598  686035780142297088           6.860340e+17         4.196984e+09   
1605  685681090388975616           6.855479e+17         4.196984e+09   
1618  684969860808454144           6.849598e+17         

We can exclude "in_reply_to_status_id and in_reply_to_user_id" from the data as "it is an indicator that the the @username" of the sender of the picture is included in the text (source: Tweepy API in the API.update_status section --  http://docs.tweepy.org/en/latest/api.html?highlight=lang#API.search

Next, we will examine the tweets file, obtained from querying the Tweepy API.

In [29]:
# display the contents of tweets dataset
tweets.head()

created_at                  id              id_str  \
0 2017-08-01 16:23:56+00:00  892420643555336193  892420643555336192   
1 2017-08-01 00:17:27+00:00  892177421306343426  892177421306343424   
2 2017-07-31 00:18:03+00:00  891815181378084864  891815181378084864   
3 2017-07-30 15:58:51+00:00  891689557279858688  891689557279858688   
4 2017-07-29 16:00:24+00:00  891327558926688256  891327558926688256   

                                           full_text  truncated  \
0  This is Phineas. He's a mystical boy. Only eve...      False   
1  This is Tilly. She's just checking pup on you....      False   
2  This is Archie. He is a rare Norwegian Pouncin...      False   
3  This is Darla. She commenced a snooze mid meal...      False   
4  This is Franklin. He would like you to stop ca...      False   

  display_text_range                                           entities  \
0            [0, 85]  {'hashtags': [], 'symbols': [], 'user_mentions...   
1           [0, 138]  {'hashtags': [], 'symbols': [], 'user_mentions...   
2           [0, 121]  {'hashtags': [], 'symbols': [], 'user_mentions...   
3            [0, 79]  {'hashtags': [], 'symbols': [], 'user_mentions...   
4           [0, 138]  {'hashtags': [{'text': 'BarkWeek', 'indices': ...   

                                   extended_entities  \
0  {'media': [{'id': 892420639486877696, 'id_str'...   
1  {'media': [{'id': 892177413194625024, 'id_str'...   
2  {'media': [{'id': 891815175371796480, 'id_str'...   
3  {'media': [{'id': 891689552724799489, 'id_str'...   
4  {'media': [{'id': 891327551943041024, 'id_str'...   

                                              source  in_reply_to_status_id  \
0  <a href="http://twitter.com/download/iphone" r...                    NaN   
1  <a href="http://twitter.com/download/iphone" r...                    NaN   
2  <a href="http://twitter.com/download/iphone" r...                    NaN   
3  <a href="http://twitter.com/download/iphone" r...                    NaN   
4  <a href="http://twitter.com/download/iphone" r...                    NaN   

   ...  favorited  retweeted  possibly_sensitive  \
0  ...      False      False                 0.0   
1  ...      False      False                 0.0   
2  ...      False      False                 0.0   
3  ...      False      False                 0.0   
4  ...      False      False                 0.0   

  possibly_sensitive_appealable lang  retweeted_status  quoted_status_id  \
0                           0.0   en               NaN               NaN   
1                           0.0   en               NaN               NaN   
2                           0.0   en               NaN               NaN   
3                           0.0   en               NaN               NaN   
4                           0.0   en               NaN               NaN   

  quoted_status_id_str  quoted_status_permalink  quoted_status  
0                  NaN                      NaN            NaN  
1                  NaN                      NaN            NaN  
2                  NaN                      NaN            NaN  
3                  NaN                      NaN            NaN  
4                  NaN                      NaN            NaN  

[5 rows x 32 columns]

tweets also has a field called retweeted_status.  We will need to remove records that are retweeted.

In [30]:
# display the contents of retweeted_status
tweets['retweeted_status'].sample(1000)

1631                                                  NaN
22                                                    NaN
1594                                                  NaN
1727                                                  NaN
639                                                   NaN
1388                                                  NaN
1262                                                  NaN
1566                                                  NaN
1604                                                  NaN
2095                                                  NaN
1249                                                  NaN
1018                                                  NaN
904                                                   NaN
1830                                                  NaN
929                                                   NaN
5                                                     NaN
1895                                                  NaN
1875          

We see from the sample above there are records that will need to be deleted.  Now, let's look at the structure of the tweets dataset.

In [31]:
# display the structure of the tweets dataset
tweets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2331 entries, 0 to 2330
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype              
---  ------                         --------------  -----              
 0   created_at                     2331 non-null   datetime64[ns, UTC]
 1   id                             2331 non-null   int64              
 2   id_str                         2331 non-null   int64              
 3   full_text                      2331 non-null   object             
 4   truncated                      2331 non-null   bool               
 5   display_text_range             2331 non-null   object             
 6   entities                       2331 non-null   object             
 7   extended_entities              2059 non-null   object             
 8   source                         2331 non-null   object             
 9   in_reply_to_status_id          77 non-null     float64            
 10  in_reply_to_status_id_st

Looking at the file above, we see the following issues: 

* id should be renamed tweet_id
* in_reply_to_status_id, in_reply_to_status_id_str, in_reply_to_user_id, and in_reply_to_user_id_str are float.  in_reply_to_status_id and in_reply_to_user_id should be integer.  in_reply_to_status_id_str and in_reply_to_user_id should be string
* geo appears to have no values
* coordinates appers to have no values
* place appears to have only 1 value
* contributors appears to have no values
* there are 163 retweeted_status records.  Need to delete them.
* quoted_status_id should be an integer and seems to have very few records (26)
* quoted status_id_str should be a string and seems to have very few records (26)


In [32]:
# dispays the contents of retweeted
tweets['retweeted'].value_counts()

False    2331
Name: retweeted, dtype: int64

The retweeted field does not provide any useful information as all records are false.

In [33]:
# dispays the contents of quoted_status
tweets['quoted_status'].sample(1000)

2195                                                  NaN
1110                                                  NaN
98                                                    NaN
1128                                                  NaN
2125                                                  NaN
904                                                   NaN
2                                                     NaN
1615                                                  NaN
1975                                                  NaN
226                                                   NaN
113                                                   NaN
1508                                                  NaN
360                                                   NaN
363                                                   NaN
319                                                   NaN
740                                                   NaN
1669                                                  NaN
1356          

The quoted_status field does not provide any information that is relevant to this analysis, so, it will be dropped.

In [34]:
# provide statistics for the tweets file
tweets.describe()

id        id_str  in_reply_to_status_id  \
count  2.331000e+03  2.331000e+03           7.700000e+01   
mean   7.419079e+17  7.419079e+17           7.440692e+17   
std    6.823170e+16  6.823170e+16           7.524295e+16   
min    6.660209e+17  6.660209e+17           6.658147e+17   
25%    6.782670e+17  6.782670e+17           6.757073e+17   
50%    7.182469e+17  7.182469e+17           7.032559e+17   
75%    7.986692e+17  7.986692e+17           8.233264e+17   
max    8.924206e+17  8.924206e+17           8.862664e+17   

       in_reply_to_status_id_str  in_reply_to_user_id  \
count               7.700000e+01         7.700000e+01   
mean                7.440692e+17         2.040329e+16   
std                 7.524295e+16         1.260797e+17   
min                 6.658147e+17         1.185634e+07   
25%                 6.757073e+17         3.589728e+08   
50%                 7.032559e+17         4.196984e+09   
75%                 8.233264e+17         4.196984e+09   
max                 8.862664e+17         8.405479e+17   

       in_reply_to_user_id_str  geo  coordinates  contributors  retweet_count  \
count             7.700000e+01  0.0          0.0           0.0    2331.000000   
mean              2.040329e+16  NaN          NaN           NaN    2668.567568   
std               1.260797e+17  NaN          NaN           NaN    4512.982811   
min               1.185634e+07  NaN          NaN           NaN       1.000000   
25%               3.589728e+08  NaN          NaN           NaN     541.000000   
50%               4.196984e+09  NaN          NaN           NaN    1249.000000   
75%               4.196984e+09  NaN          NaN           NaN    3101.500000   
max               8.405479e+17  NaN          NaN           NaN   76718.000000   

       favorite_count  possibly_sensitive  possibly_sensitive_appealable  \
count     2331.000000              2196.0                         2196.0   
mean      7486.584299                 0.0                            0.0   
std      11622.376482                 0.0                            0.0   
min          0.000000                 0.0                            0.0   
25%       1303.000000                 0.0                            0.0   
50%       3253.000000                 0.0                            0.0   
75%       9168.500000                 0.0                            0.0   
max     154488.000000                 0.0                            0.0   

       quoted_status_id  quoted_status_id_str  
count      2.600000e+01          2.600000e+01  
mean       8.113972e+17          8.113972e+17  
std        6.295843e+16          6.295843e+16  
min        6.721083e+17          6.721083e+17  
25%        7.761338e+17          7.761338e+17  
50%        8.281173e+17          8.281173e+17  
75%        8.637581e+17          8.637581e+17  
max        8.860534e+17          8.860534e+17

Looking at the data above, we can see confirmation that geo, coordinates, contributors, possibly_sensitive, and possibly sensitive_appealable do not really have any useful data and will be removed.

Now, let's explore the text field in further detail.

In [35]:
# change system option to allow for wider display of a variable
pd.set_option('display.max_colwidth', 200)
# displays the contents of the in_reply_to_user_id field
tweet_check = tweets[tweets.in_reply_to_user_id >0]

In [36]:
# print the contens of full_text
for i in tweet_check.full_text:
    print(tweet_check.full_text)

29                                                                @NonWhiteHat @MayhewMayhem omg hello tanner you are a scary good boy 12/10 would pet with extreme caution
54                                                                              @roushfenway These are good dogs but 17/10 is an emotional impulse rating. More like 13/10s
63                                                                                                                                          @RealKentMurphy 14/10 confirmed
109                                                                                                            @ComplicitOwl @ShopWeRateDogs &gt;10/10 is reserved for dogs
142                                  @Jack_Septic_Eye I'd need a few more pics to polish a full analysis, but based on the good boy content above I'm leaning towards 12/10
143     Ladies and gentlemen... I found Pipsy. He may have changed his name to Pablo, but he never changed his love for the sea. Pupgraded t

29                                                                @NonWhiteHat @MayhewMayhem omg hello tanner you are a scary good boy 12/10 would pet with extreme caution
54                                                                              @roushfenway These are good dogs but 17/10 is an emotional impulse rating. More like 13/10s
63                                                                                                                                          @RealKentMurphy 14/10 confirmed
109                                                                                                            @ComplicitOwl @ShopWeRateDogs &gt;10/10 is reserved for dogs
142                                  @Jack_Septic_Eye I'd need a few more pics to polish a full analysis, but based on the good boy content above I'm leaning towards 12/10
143     Ladies and gentlemen... I found Pipsy. He may have changed his name to Pablo, but he never changed his love for the sea. Pupgraded t

Looking at the full text, the following can be observed:
* There are tweet users at the beginning of the text field (@serial, @MrRoles, etc.  These could be stripped out into their own column.
* Rating is included in text, but could be moved into its own field.  Since it was, it can be removed from this field.
* the Twitter url for the tweet is included.  It should be stripped and moved into its own field.

Next, let's look at the lang variable.

In [37]:
# displays the contents of the lang variable
tweets['lang'].value_counts()

en     2313
und       7
nl        3
in        3
es        1
tl        1
ro        1
et        1
eu        1
Name: lang, dtype: int64

Spell out the different languages of the tweets. en = English, es = Spanish , tl = Tagalong , ro = Romanian , nl = Nederlands, in = Indonesian, et = Estonian, und = Undetermined, eu = Basque

ISO 639-1 codes are used by Tweepy. I found the codes for all of the above except "und" which I took to be undetermined. https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#ET https://www.sitepoint.com/iso-2-letter-language-codes.

In [38]:
# use query to display dataset contents when lang = und
tweets.query('lang == "und"')

created_at                  id              id_str  \
31   2017-07-15 02:45:48+00:00  886054160059072513  886054160059072512   
278  2017-03-04 22:12:52+00:00  838150277551247360  838150277551247360   
393  2017-01-23 00:56:15+00:00  823333489516937216  823333489516937216   
602  2016-11-08 23:01:49+00:00  796125600683540480  796125600683540480   
1056 2016-06-04 00:32:32+00:00  738891149612572673  738891149612572672   
1499 2016-01-22 18:49:36+00:00  690607260360429569  690607260360429568   
1889 2015-12-08 20:53:11+00:00  674330906434379776  674330906434379776   

                                               full_text  truncated  \
31    RT @Athletics: 12/10 #BATP https://t.co/WxwJmvjfxo      False   
278                                   @markhoppus 182/10      False   
393                                 @HistoryInPics 13/10      False   
602           #ImWithThor 13/10\nhttps://t.co/a18mzkhTf6      False   
1056                                  @mount_alex3 13/10      False   
1499                               12/10 @LightningHoltt      False   
1889                                        13/10\n@ABC7      False   

     display_text_range  \
31              [0, 50]   
278            [12, 18]   
393            [15, 20]   
602             [0, 41]   
1056           [13, 18]   
1499            [0, 21]   
1889            [0, 11]   

                                                                                                                                                                                                     entities  \
31    {'hashtags': [{'text': 'BATP', 'indices': [21, 26]}], 'symbols': [], 'user_mentions': [{'screen_name': 'Athletics', 'name': 'Oakland A's', 'id': 19607400, 'id_str': '19607400', 'indices': [3, 13]}...   
278                     {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'markhoppus', 'name': 'black lives matter', 'id': 21955058, 'id_str': '21955058', 'indices': [0, 11]}], 'urls': []}   
393             {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'HistoryInPics', 'name': 'History In Pictures', 'id': 1582853809, 'id_str': '1582853809', 'indices': [0, 14]}], 'urls': []}   
602   {'hashtags': [{'text': 'ImWithThor', 'indices': [0, 11]}], 'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/a18mzkhTf6', 'expanded_url': 'https://twitter.com/king5seattle/status/...   
1056                         {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'mount_alex3', 'name': 'Alex Mount', 'id': 358972768, 'id_str': '358972768', 'indices': [0, 12]}], 'urls': []}   
1499                       {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'LightningHoltt', 'name': 'Ryan Holt', 'id': 467036706, 'id_str': '467036706', 'indices': [6, 21]}], 'urls': []}   
1889                        {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'ABC7', 'name': 'ABC7 Eyewitness News', 'id': 16374678, 'id_str': '16374678', 'indices': [6, 11]}], 'urls': []}   

     extended_entities  \
31                 NaN   
278                NaN   
393                NaN   
602                NaN   
1056               NaN   
1499               NaN   
1889               NaN   

                                                                                  source  \
31    <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
278   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
393   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
602   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1056  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1499  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1889  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

      in_reply_to_stat

In [39]:
# use query to display dataset contents when lang = in
tweets.query('lang == "in"')

created_at                  id              id_str  \
158  2017-05-04 17:01:34+00:00  860177593139703809  860177593139703808   
848  2016-08-05 21:19:27+00:00  761672994376806400  761672994376806400   
1642 2015-12-31 22:57:47+00:00  682697186228989953  682697186228989952   

                                                                                                                                         full_text  \
158   RT @dog_rates: Ohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboy. 10/10 for all (by happytailsresort) https://t.c…   
848       Ohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboy. 10/10 for all (by happytailsresort) https://t.co/EY8kEFuzK7   
1642                                                                           NAAAAAAA ZAPENYAAAAA MABADI-CHIBAWAAA 12/10 https://t.co/Ny4iM6FDtz   

      truncated display_text_range  \
158       False           [0, 140]   
848       False           [0, 112]   
1642      False            [0, 67]   

                                                                                                                                                                                                     entities  \
158                         {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'dog_rates', 'name': 'WeRateDogs®', 'id': 4196983835, 'id_str': '4196983835', 'indices': [3, 13]}], 'urls': []}   
848   {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 761672828462718981, 'id_str': '761672828462718981', 'indices': [113, 136], 'media_url': 'http://pbs.twimg.com/ext_...   
1642  {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 682697175697088514, 'id_str': '682697175697088514', 'indices': [44, 67], 'media_url': 'http://pbs.twimg.com/media/...   

                                                                                                                                                                                            extended_entities  \
158                                                                                                                                                                                                       NaN   
848   {'media': [{'id': 761672828462718981, 'id_str': '761672828462718981', 'indices': [113, 136], 'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/761672828462718981/pu/img/R00UYAAWB3GtuHdI.jpg', ...   
1642  {'media': [{'id': 682697175697088514, 'id_str': '682697175697088514', 'indices': [44, 67], 'media_url': 'http://pbs.twimg.com/media/CXltdtaWYAIuX_V.jpg', 'media_url_https': 'https://pbs.twimg.com/...   

                                                                                  source  \
158   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
848   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1642  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

      in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
158                     NaN  ...      False      False                 NaN   
848                     NaN  ...      False      False                 0.0   
1642                    NaN  ...      False      False                 0.0   

     possibly_sensitive_appealable lang  \
158                            NaN   in   
848                            0.0   in   
1642                           0.0   in   

                                                                                                                                                                                             retweeted_status  \
158   {'created_at': 'Fri Aug 05 21:19:27 +0000 2016', 'id': 761672994376806400, 'id_str': '761672994376806400', 'full_text': 'Ohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboyohboy...   
848                   

In [40]:
# use query to display dataset contents when lang = nl
tweets.query('lang == "nl"')

created_at                  id              id_str  \
1635 2016-01-02 01:33:43+00:00  683098815881154561  683098815881154560   
1861 2015-12-10 03:19:24+00:00  674790488185167872  674790488185167872   
2253 2015-11-19 20:14:03+00:00  667435689202614272  667435689202614272   

                                                                        full_text  \
1635  aahhhhkslaldhwnxmzbbs 12/10 for being da smooshiest https://t.co/UOPdXmUz4H   
1861                              ER... MER... GERD 13/10 https://t.co/L1puJISV1a   
2253                                      Ermergerd 12/10 https://t.co/PQni2sjPsm   

      truncated display_text_range  \
1635      False            [0, 75]   
1861      False            [0, 47]   
2253      False            [0, 39]   

                                                                                                                                                                                                     entities  \
1635  {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 683098811808518144, 'id_str': '683098811808518144', 'indices': [52, 75], 'media_url': 'http://pbs.twimg.com/media/...   
1861  {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 674790484284436480, 'id_str': '674790484284436480', 'indices': [24, 47], 'media_url': 'http://pbs.twimg.com/media/...   
2253  {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 667435686304342017, 'id_str': '667435686304342017', 'indices': [16, 39], 'media_url': 'http://pbs.twimg.com/media/...   

                                                                                                                                                                                            extended_entities  \
1635  {'media': [{'id': 683098811808518144, 'id_str': '683098811808518144', 'indices': [52, 75], 'media_url': 'http://pbs.twimg.com/media/CXrawAhWkAAWSxC.jpg', 'media_url_https': 'https://pbs.twimg.com/...   
1861  {'media': [{'id': 674790484284436480, 'id_str': '674790484284436480', 'indices': [24, 47], 'media_url': 'http://pbs.twimg.com/media/CV1WXsmWcAAgQ56.jpg', 'media_url_https': 'https://pbs.twimg.com/...   
2253  {'media': [{'id': 667435686304342017, 'id_str': '667435686304342017', 'indices': [16, 39], 'media_url': 'http://pbs.twimg.com/media/CUM1OHCW4AEgGSi.jpg', 'media_url_https': 'https://pbs.twimg.com/...   

                                                                                  source  \
1635  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1861  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
2253  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

      in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
1635                    NaN  ...      False      False                 0.0   
1861                    NaN  ...      False      False                 0.0   
2253                    NaN  ...      False      False                 0.0   

     possibly_sensitive_appealable lang  retweeted_status  quoted_status_id  \
1635                           0.0   nl               NaN               NaN   
1861                           0.0   nl               NaN               NaN   
2253                           0.0   nl               NaN               NaN   

     quoted_status_id_str  quoted_status_permalink  quoted_status  
1635                  NaN                      NaN            NaN  
1861                  NaN                      NaN            NaN  
2253                  NaN                      NaN            NaN  

[3 rows x 32 columns]

In [41]:
# use query to display dataset contents when lang = eu
tweets.query('lang == "eu"')

created_at                  id              id_str  \
958 2016-07-03 00:43:15+00:00  749403093750648834  749403093750648832   

                                                                                                                                     full_text  \
958  Duuun dun... duuun dun... dunn  dun. dunn dun. dun dun dun dun dun dun dun dun dun dun dun dun dun dun dun. 10/10 https://t.co/9qdJ2Q1Cwx   

     truncated display_text_range  \
958      False           [0, 113]   

                                                                                                                                                                                                    entities  \
958  {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 749403085643063300, 'id_str': '749403085643063300', 'indices': [114, 137], 'media_url': 'http://pbs.twimg.com/medi...   

                                                                                                                                                                                           extended_entities  \
958  {'media': [{'id': 749403085643063300, 'id_str': '749403085643063300', 'indices': [114, 137], 'media_url': 'http://pbs.twimg.com/media/CmZqIslWIAQFiqe.jpg', 'media_url_https': 'https://pbs.twimg.co...   

                                                                                 source  \
958  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

     in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
958                    NaN  ...      False      False                 0.0   

    possibly_sensitive_appealable lang  retweeted_status  quoted_status_id  \
958                           0.0   eu               NaN               NaN   

    quoted_status_id_str  quoted_status_permalink  quoted_status  
958                  NaN                      NaN            NaN  

[1 rows x 32 columns]

In [42]:
# use query to display dataset contents when lang = es
tweets.query('lang == "es"')

created_at                  id              id_str  \
1321 2016-03-01 02:19:31+00:00  704491224099647488  704491224099647488   

                full_text  truncated display_text_range  \
1321  13/10 hero af\n@ABC      False            [0, 18]   

                                                                                                                                                                   entities  \
1321  {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'ABC', 'name': 'ABC News', 'id': 28785486, 'id_str': '28785486', 'indices': [14, 18]}], 'urls': []}   

     extended_entities  \
1321               NaN   

                                                                                  source  \
1321  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

      in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
1321           7.044857e+17  ...      False      False                 NaN   

     possibly_sensitive_appealable lang  retweeted_status  quoted_status_id  \
1321                           NaN   es               NaN               NaN   

     quoted_status_id_str  quoted_status_permalink  quoted_status  
1321                  NaN                      NaN            NaN  

[1 rows x 32 columns]

In [43]:
# use query to display dataset contents when lang = tl
tweets.query('lang == "tl"')

created_at                  id              id_str  \
2164 2015-11-24 01:42:25+00:00  668967877119254528  668967877119254528   

                           full_text  truncated display_text_range  \
2164  12/10 good shit Bubka\n@wane15      False            [0, 29]   

                                                                                                                                                                     entities  \
2164  {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'wane15', 'name': 'WANE 15', 'id': 21435658, 'id_str': '21435658', 'indices': [22, 29]}], 'urls': []}   

     extended_entities  \
2164               NaN   

                                                                                  source  \
2164  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

      in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
2164           6.689207e+17  ...      False      False                 NaN   

     possibly_sensitive_appealable lang  retweeted_status  quoted_status_id  \
2164                           NaN   tl               NaN               NaN   

     quoted_status_id_str  quoted_status_permalink  quoted_status  
2164                  NaN                      NaN            NaN  

[1 rows x 32 columns]

In [44]:
# use query to display dataset contents when lang = ro
tweets.query('lang == "ro"')

created_at                  id              id_str  \
2235 2015-11-20 03:51:47+00:00  667550882905632768  667550882905632768   

                                                                                                     full_text  \
2235  RT @dogratingrating: Unoriginal idea. Blatant plagiarism. Curious grammar. -5/10 https://t.co/r7XzeQZWzb   

      truncated display_text_range  \
2235      False           [0, 104]   

                                                                                                                                                                                                     entities  \
2235  {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'dogratingrating', 'name': 'We Rate Dog Ratings', 'id': 4296831739, 'id_str': '4296831739', 'indices': [3, 19]}], 'urls': [], 'med...   

                                                                                                                                                                                            extended_entities  \
2235  {'media': [{'id': 667548406944960512, 'id_str': '667548406944960512', 'indices': [81, 104], 'media_url': 'http://pbs.twimg.com/media/CUObvUJVEAAnYPF.jpg', 'media_url_https': 'https://pbs.twimg.com...   

                                                                  source  \
2235  <a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>   

      in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
2235                    NaN  ...      False      False                 0.0   

     possibly_sensitive_appealable lang  \
2235                           0.0   ro   

                                                                                                                                                                                             retweeted_status  \
2235  {'created_at': 'Fri Nov 20 03:41:59 +0000 2015', 'id': 667548415174144001, 'id_str': '667548415174144001', 'full_text': 'Unoriginal idea. Blatant plagiarism. Curious grammar. -5/10 https://t.co/r7...   

      quoted_status_id quoted_status_id_str  quoted_status_permalink  \
2235               NaN                  NaN                      NaN   

      quoted_status  
2235            NaN  

[1 rows x 32 columns]

In [45]:
# use query to display dataset contents when lang = et
tweets.query('lang == "et"')

created_at                  id              id_str  \
2259 2015-11-19 04:05:59+00:00  667192066997374976  667192066997374976   

                                                                                                full_text  \
2259  *takes several long deep breaths* omg omg oMG OMG OMG OMGSJYBSNDUYWJO 12/10 https://t.co/QCugm5ydl6   

      truncated display_text_range  \
2259      False            [0, 99]   

                                                                                                                                                                                                     entities  \
2259  {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 667192061259620352, 'id_str': '667192061259620352', 'indices': [76, 99], 'media_url': 'http://pbs.twimg.com/media/...   

                                                                                                                                                                                            extended_entities  \
2259  {'media': [{'id': 667192061259620352, 'id_str': '667192061259620352', 'indices': [76, 99], 'media_url': 'http://pbs.twimg.com/media/CUJXpRBXIAAN0yz.jpg', 'media_url_https': 'https://pbs.twimg.com/...   

                                                                                  source  \
2259  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

      in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
2259                    NaN  ...      False      False                 0.0   

     possibly_sensitive_appealable lang  retweeted_status  quoted_status_id  \
2259                           0.0   et               NaN               NaN   

     quoted_status_id_str  quoted_status_permalink  quoted_status  
2259                  NaN                      NaN            NaN  

[1 rows x 32 columns]

Only one of the non-english texts appear to be non-English. Therefore, we will delete this column as it will not add any value to the analysis.

Based on a review of this column, recommend deleting the "lang" variable.  This look like english or jibberish.

In [46]:
# look at the contents of truncated
tweets['truncated'].value_counts()

False    2331
Name: truncated, dtype: int64

Remove the truncated column as the only value is "False".

In [47]:
# look at the contents of display_text_range
tweets['display_text_range'].sample(20)

1685    [0, 123]
52       [0, 67]
1066    [0, 116]
1649    [0, 137]
1526    [0, 139]
2179    [0, 139]
131     [0, 140]
881     [0, 113]
893     [0, 102]
252     [0, 140]
772     [0, 113]
1404     [0, 92]
389      [0, 79]
2017    [0, 136]
1425    [0, 124]
235      [0, 97]
1200     [0, 69]
2254     [0, 65]
940      [0, 80]
1591    [0, 135]
Name: display_text_range, dtype: object

Remove the display_text_range column as it only provides the display text range.

In [48]:
# look at the contents of entities
tweets['entities'].sample(5)

198     {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 852672601419911169, 'id_str': '852672601419911169', 'indices': [114, 137], 'media_url': 'http://pbs.twimg.com/medi...
1590    {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 685307443652472833, 'id_str': '685307443652472833', 'indices': [117, 140], 'media_url': 'http://pbs.twimg.com/medi...
1476    {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 692158336909852672, 'id_str': '692158336909852672', 'indices': [106, 129], 'media_url': 'http://pbs.twimg.com/medi...
169     {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 857746390159675396, 'id_str': '857746390159675396', 'indices': [138, 161], 'media_url': 'http://pbs.twimg.com/medi...
1002    {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 746131866353270785, 'id_str': '746131866353270785', 'indices': [101, 124], 'me

Remove the entities column as it does not provide any data that will be used in the analysis.

In [49]:
#display the contents of is_quote_status
tweets['is_quote_status'].value_counts()

False    2300
True       31
Name: is_quote_status, dtype: int64

In [50]:
# use query to look at dataset when is_quote status = True
tweets.query('is_quote_status == True').sample(2)

created_at                  id              id_str  \
82   2017-06-18 20:30:39+00:00  876537666061221889  876537666061221888   
1213 2016-03-22 16:06:19+00:00  712309440758808576  712309440758808576   

                                                                                                                                            full_text  \
82      I can say with the pupmost confidence that the doggos who assisted with this search are heroic as h*ck. 14/10 for all https://t.co/8yoc1CNTsu   
1213  Reminder that we made our first set of stickers available! All are 12/10 would stick\nUse code "pupper" at checkout🐶\n\nhttps://t.co/kJIMNyMNKV   

      truncated display_text_range  \
82        False           [0, 117]   
1213      False           [0, 140]   

                                                                                                                                                                                                     entities  \
82    {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/8yoc1CNTsu', 'expanded_url': 'https://twitter.com/mpstowerham/status/876162994446753793', 'display_url': 'twitte...   
1213  {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/kJIMNyMNKV', 'expanded_url': 'https://twitter.com/stickergrub/status/709919141004595201', 'display_url': 'twitte...   

     extended_entities  \
82                 NaN   
1213               NaN   

                                                                                  source  \
82    <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1213  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

      in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
82                      NaN  ...      False      False                 0.0   
1213                    NaN  ...      False      False                 0.0   

     possibly_sensitive_appealable lang  retweeted_status  quoted_status_id  \
82                             0.0   en               NaN      8.761630e+17   
1213                           0.0   en               NaN      7.099191e+17   

     quoted_status_id_str  \
82           8.761630e+17   
1213         7.099191e+17   

                                                                                                                                    quoted_status_permalink  \
82    {'url': 'https://t.co/8yoc1CNTsu', 'expanded': 'https://twitter.com/mpstowerham/status/876162994446753793', 'display': 'twitter.com/mpstowerham/st…'}   
1213  {'url': 'https://t.co/kJIMNyMNKV', 'expanded': 'https://twitter.com/stickergrub/status/709919141004595201', 'display': 'twitter.com/stickergrub/st…'}   

                                                                                                                                                                                                quoted_status  
82    {'created_at': 'Sat Jun 17 19:41:50 +0000 2017', 'id': 876162994446753793, 'id_str': '876162994446753793', 'full_text': 'These are the amazing dogs who searched the #GrenfellTower with their fire ...  
1213  {'created_at': 'Wed Mar 16 01:48:07 +0000 2016', 'id': 709919141004595201, 'id_str': '709919141004595201', 'full_text': 'We partnered w/ @dog_rates to bring you the cutest damn stickers you've eve...  

[2 rows x 32 columns]

In [51]:
# use query to look at dataset when is_quote status = False
tweets.query('is_quote_status == False').sample(2)

created_at                  id              id_str  \
399  2017-01-21 03:29:14+00:00  822647212903690241  822647212903690240   
1568 2016-01-11 03:47:50+00:00  686394059078897668  686394059078897664   

                                                                                                                                   full_text  \
399    RT @dog_rates: This is Paisley. She really wanted to be president this time. Dreams officially crushed. 13/10 https://t.co/liJGwMp17E   
1568  This pup's having a nightmare that he forgot to type a paper due first thing in the morning. 12/10 (vid by ... https://t.co/CufnbUT0pB   

      truncated display_text_range  \
399       False           [0, 133]   
1568      False           [0, 134]   

                                                                                                                                                                                                     entities  \
399   {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'dog_rates', 'name': 'WeRateDogs®', 'id': 4196983835, 'id_str': '4196983835', 'indices': [3, 13]}], 'urls': [], 'media': [{'id': 8...   
1568  {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/CufnbUT0pB', 'expanded_url': 'https://vine.co/v/iMqBebnOvav', 'display_url': 'vine.co/v/iMqBebnOvav', 'indices':...   

                                                                                                                                                                                            extended_entities  \
399   {'media': [{'id': 822489041455157248, 'id_str': '822489041455157248', 'indices': [110, 133], 'media_url': 'http://pbs.twimg.com/media/C2oRbOuWEAAbVSl.jpg', 'media_url_https': 'https://pbs.twimg.co...   
1568                                                                                                                                                                                                      NaN   

                                                                                  source  \
399   <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1568                     <a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>   

      in_reply_to_status_id  ...  favorited  retweeted  possibly_sensitive  \
399                     NaN  ...      False      False                 0.0   
1568                    NaN  ...      False      False                 0.0   

     possibly_sensitive_appealable lang  \
399                            0.0   en   
1568                           0.0   en   

                                                                                                                                                                                             retweeted_status  \
399   {'created_at': 'Fri Jan 20 17:00:46 +0000 2017', 'id': 822489057087389700, 'id_str': '822489057087389700', 'full_text': 'This is Paisley. She really wanted to be president this time. Dreams offici...   
1568                                                                                                                                                                                                      NaN   

      quoted_status_id quoted_status_id_str  quoted_status_permalink  \
399                NaN                  NaN                      NaN   
1568               NaN                  NaN                      NaN   

      quoted_status  
399             NaN  
1568            NaN  

[2 rows x 32 columns]

Drop is_quote_status as it does not add value to the analysis.

In [52]:
# lood at contents of quoted_status_permalink
tweets['quoted_status_permalink'].sample(100)

598                                                                                                                                                       NaN
159                                                                                                                                                       NaN
1377                                                                                                                                                      NaN
1657                                                                                                                                                      NaN
1137                                                                                                                                                      NaN
537                                                                                                                                                       NaN
40                                                  

The quoted_status_permalink variable does not appear to add value to the analysis.

Now, let's look at the image_predictions file.

In [53]:
# look at contents of image_predictions
image_predictions.head()

tweet_id                                          jpg_url  \
0  666020888022790149  https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg   
1  666029285002620928  https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg   
2  666033412701032449  https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg   
3  666044226329800704  https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg   
4  666049248165822465  https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg   

   img_num                      p1   p1_conf  p1_dog                  p2  \
0        1  Welsh_springer_spaniel  0.465074    True              collie   
1        1                 redbone  0.506826    True  miniature_pinscher   
2        1         German_shepherd  0.596461    True            malinois   
3        1     Rhodesian_ridgeback  0.408143    True             redbone   
4        1      miniature_pinscher  0.560311    True          Rottweiler   

    p2_conf  p2_dog                   p3   p3_conf  p3_dog  
0  0.156665    True    Shetland_sheepdog  0.061428    True  
1  0.074192    True  Rhodesian_ridgeback  0.072010    True  
2  0.138584    True           bloodhound  0.116197    True  
3  0.360687    True   miniature_pinscher  0.222752    True  
4  0.243682    True             Doberman  0.154629    True

Looking at the data, above, we see the following:

* The picture is contained in jpg_url
* p1, p2, p3 represent the predicted dog breed.  Need to spell out prediction.
* p1_conf, p2_conf, p3_conf represent confidence in the prediction.  Need to spell out prediction.
* Notice that p1, p2 and p3 dog names are lower_case.  Need to make first letter uppercase.
* Breeds with two words have an underscore.  Should be a space.

Next, we need to see if there are any duplicate columns in the datasets.  The code below will check.

In [54]:
# check for duplicate columns in all three of the datasets
all_columns = pd.Series(list(twitter_archive_enhanced) + list(image_predictions) + list(tweets))
all_columns[all_columns.duplicated()]

17                 tweet_id
37                   source
38    in_reply_to_status_id
40      in_reply_to_user_id
dtype: object

tweet_id, source, in_reply_to_status_id and in_reply_to_user_id are duplicated.  Since tweet_id = id is common to all files, will need to keep that as the primary key for all datasets.

Now, let's look at the image_predictions data structure.

In [55]:
# look at the structure of the image_predictions dataset
image_predictions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   tweet_id  2075 non-null   int64  
 1   jpg_url   2075 non-null   object 
 2   img_num   2075 non-null   int64  
 3   p1        2075 non-null   object 
 4   p1_conf   2075 non-null   float64
 5   p1_dog    2075 non-null   bool   
 6   p2        2075 non-null   object 
 7   p2_conf   2075 non-null   float64
 8   p2_dog    2075 non-null   bool   
 9   p3        2075 non-null   object 
 10  p3_conf   2075 non-null   float64
 11  p3_dog    2075 non-null   bool   
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB


Based on what we know about the file, the structure seems ok at first glance.  We should look at p1_dog, p2_dog and p3_dog to understand what appears in those variables.

In [56]:
# look at the structure of p1_dog
image_predictions['p1_dog'].value_counts()

True     1532
False     543
Name: p1_dog, dtype: int64

In [57]:
# look at the dataset when p1_dog is false
image_predictions.query('p1_dog == False')

tweet_id  \
6     666051853826850816   
8     666057090499244032   
17    666104133288665088   
18    666268910803644416   
21    666293911632134144   
22    666337882303524864   
25    666362758909284353   
29    666411507551481857   
33    666430724426358785   
43    666776908487630848   
45    666786068205871104   
50    666837028449972224   
51    666983947667116034   
52    666996132027977728   
53    667012601033924608   
56    667065535570550784   
69    667188689915760640   
73    667369227918143488   
77    667437278097252352   
78    667443425659232256   
87    667524857454854144   
93    667549055577362432   
94    667550882905632768   
95    667550904950915073   
96    667724302356258817   
98    667766675769573376   
100   667782464991965184   
103   667806454573760512   
106   667866724293877760   
107   667873844930215936   
108   667878741721415682   
112   667911425562669056   
113   667915453470232577   
115   667937095915278337   
117   668142349051129856   
118   668154635664932864   
123   668226093875376128   
126   668256321989451776   
130   668291999406125056   
131   668297328638447616   
132   668466899341221888   
133   668480044826800133   
140   668544745690562560   
142   668614819948453888   
143   668620235289837568   
145   668625577880875008   
150   668641109086707712   
151   668643542311546881   
152   668645506898350081   
158   668872652652679168   
163   668960084974809088   
166   668981893510119424   
167   668986018524233728   
168   668988183816871936   
170   668992363537309700   
171   668994913074286592   
174   669015743032369152   
177   669214165781868544   
179   669324657376567296   
182   669351434509529089   
183   669353438988365824   
193   669571471778410496   
195   669583744538451968   
198   669625907762618368   
199   669661792646373376   
201   669682095984410625   
203   669749430875258880   
205   669923323644657664   
209   669972011175813120   
210   669993076832759809   
212   670037189829525505   
213   670040295598354432   
215   670055038660800512   
217   670069087419133954   
219   670079681849372674   
226   670361874861563904   
230   670408998013820928   
232   670417414769758208   
233   670420569653809152   
235   670427002554466305   
237   670433248821026816   
238   670434127938719744   
239   670435821946826752   
242   670449342516494336   
243   670452855871037440   
244   670465786746662913   
245   670468609693655041   
246   670474236058800128   
247   670668383499735048   
253   670727704916926465   
254   670733412878163972   
260   670783437142401025   
261   670786190031921152   
263   670792680469889025   
270   670822709593571328   
272   670826280409919488   
275   670838202509447168   
277   670842764863651840   
281   671122204919246848   
284   671141549288370177   
288   671159727754231808   
289   671163268581498880   
290   671166507850801152   
293   671347597085433856   
296   671362598324076544   
297   671390180817915904   
300   671488513339211776   
301   671497587707535361   
303   671511350426865664   
307   671533943490011136   
309   671538301157904385   
311   671544874165002241   
312   671547767500775424   
315   671735591348891648   
317   671744970634719232   
318   671763349865160704   
321   671855973984772097   
323   671874878652489728   
324   671879137494245376   
325   671882082306625538   
329   672082170312290304   
331   672125275208069120   
335   672205392827572224   
337   672231046314901505   
342   672256522047614977   
347   672475084225949696   
352   672538107540070400   
353   672591271085670400   
357   672609152938721280   
358   672614745925664768   
361   672828477930868736   
364   672884426393653248   
365   672898206762672129   
366   672902681409806336   
369   672970152493887488   
371   672980819271634944   
372   672984142909456390   
376   673148804208660480   
383   673342308415348736   
385   673345638550134785   
390   673363615379013632   
391   673576835670777856   
393   673583

In [58]:
# look at the structure of p2_dog
image_predictions['p2_dog'].value_counts()

True     1553
False     522
Name: p2_dog, dtype: int64

There are 543 images that are 

In [59]:
# look at the structure of p3_dog
image_predictions['p3_dog'].value_counts()

True     1499
False     576
Name: p3_dog, dtype: int64

The true and false in these boolean variables indicates if the predicted image is a dog.  This description was provided by Udacity at the following link:  https://classroom.udacity.com/nanodegrees/nd002/parts/af503f34-9646-4795-a916-190ebc82cb4a/modules/14d9f5f1-9e7b-4bfb-97f3-bcdbf4a3699c/lessons/a8085857-3e28-4fc7-aeb8-da64ccbc2e20/concepts/28d4643b-3785-4700-bdee-4e5fc9963576

In [60]:
# set system max display option to view larger column witdth than default
pd.set_option('display.max_colwidth', 100)
# creates a dataset containing only retweeted rows
tweet_check = tweets[tweets.in_reply_to_user_id >0]

In [61]:
# look at the contents of full_text
for i in tweet_check.full_text:
    print(tweet_check.full_text)

29      @NonWhiteHat @MayhewMayhem omg hello tanner you are a scary good boy 12/10 would pet with extrem...
54              @roushfenway These are good dogs but 17/10 is an emotional impulse rating. More like 13/10s
63                                                                          @RealKentMurphy 14/10 confirmed
109                                            @ComplicitOwl @ShopWeRateDogs &gt;10/10 is reserved for dogs
142     @Jack_Septic_Eye I'd need a few more pics to polish a full analysis, but based on the good boy c...
143     Ladies and gentlemen... I found Pipsy. He may have changed his name to Pablo, but he never chang...
172                                                                            @Marc_IRL pixelated af 12/10
176     THIS IS CHARLIE, MARK. HE DID JUST WANT TO SAY HI AFTER ALL. PUPGRADED TO A 14/10. WOULD BE AN H...
180                  @dhmontgomery We also gave snoop dogg a 420/10 but I think that predated your research
181     @s8n You tried very 

29      @NonWhiteHat @MayhewMayhem omg hello tanner you are a scary good boy 12/10 would pet with extrem...
54              @roushfenway These are good dogs but 17/10 is an emotional impulse rating. More like 13/10s
63                                                                          @RealKentMurphy 14/10 confirmed
109                                            @ComplicitOwl @ShopWeRateDogs &gt;10/10 is reserved for dogs
142     @Jack_Septic_Eye I'd need a few more pics to polish a full analysis, but based on the good boy c...
143     Ladies and gentlemen... I found Pipsy. He may have changed his name to Pablo, but he never chang...
172                                                                            @Marc_IRL pixelated af 12/10
176     THIS IS CHARLIE, MARK. HE DID JUST WANT TO SAY HI AFTER ALL. PUPGRADED TO A 14/10. WOULD BE AN H...
180                  @dhmontgomery We also gave snoop dogg a 420/10 but I think that predated your research
181     @s8n You tried very 

29      @NonWhiteHat @MayhewMayhem omg hello tanner you are a scary good boy 12/10 would pet with extrem...
54              @roushfenway These are good dogs but 17/10 is an emotional impulse rating. More like 13/10s
63                                                                          @RealKentMurphy 14/10 confirmed
109                                            @ComplicitOwl @ShopWeRateDogs &gt;10/10 is reserved for dogs
142     @Jack_Septic_Eye I'd need a few more pics to polish a full analysis, but based on the good boy c...
143     Ladies and gentlemen... I found Pipsy. He may have changed his name to Pablo, but he never chang...
172                                                                            @Marc_IRL pixelated af 12/10
176     THIS IS CHARLIE, MARK. HE DID JUST WANT TO SAY HI AFTER ALL. PUPGRADED TO A 14/10. WOULD BE AN H...
180                  @dhmontgomery We also gave snoop dogg a 420/10 but I think that predated your research
181     @s8n You tried very 

The quality and tidyness issues I discovered are shown below:

#### Quality Issues: 

##### In the twitter_archive_enhanced file:

1) rating_numerator: Values ranging from 0 to 1776. they should be in the range from 0-13. Need to further investigate.  The WeRateDogs Wikipedia page indicated the ratings numerator is is up to 13, however, the rating structure is not followed rigidly and is considered one of the things appealing to followers. In this study, the high rating records were not removed and the analysis will not utilize the rating information

2) rating_denominator: Values exceed 10. Need to further investigate these values.  As stated above, we will not alter the ratings.

3) there are a large number of names equal to "None".  Need to see if we can obtain any of these from the text file.

3) There are 181 rows that are retweets in the twitter_archive_enhanced file.  We will need to remove these.  They can be indentified using "retweeted_status" variable.

4) Dog's name: There are a number of records with a names of "None", "an", 'the","very", "quite","one", "just", "actually","mad", "not", "officially", "infuriating", "unacceptable, "light", "his", "old", "all, "my", "such", "by, "this", "space", "life", and "a".

5) The the tweet_id should be an object/string as it is not to be used in calculting statistics. It is meant to identify the tweet.

6) The in_reply_to_status_id and in_reply_to_user_id should be an string/object, not float.

7) Retweet_count and favorite_count are float64.  They should be changed to integer as they are counts.

8) retweeted_status should be an object/string not float.

9) retweeted_status_timestam should be date/time, not object

10) using the rating numerator and rating denominator, divide to calculate the rating.


##### In the image_predictions file:

11) There are 543 images in the file that are not a picture of a dog. Need to remove these from the data.

12) Dog names in column "pl" are not capitalized in all cases.

13) Dog names should be categorical, not boolean

14) twitter_archive_enhanced "timestamp variable is an object. It should be date/time.

15) twitter_arhchive_enhanced "retweeted_status_timestamp" is an object. It should be converted to date/time.  

16) clarify the purpose of the p1,p2,p3 variables by spelling out "prediction."

17) There are a number of rows where the puppy's "name" is equal to 'None'.  Try to find the names in the texts.



##### In the tweet-json.txt file:

18) There are a number of rows that are retweets. We will need to remove these. They can be indentified using "retweeted_status" variable.

19) id should be renamed tweet_id

20) in_reply_to_status_id, in_reply_to_status_id_str, in_reply_to_user_id, and in_reply_to_user_id_str are float and should be converted to integer. 

21) quoted_status_id should be an integer and seems to have very few records (26)

22) quoted status_id_str should be an object/string 

23) The source is included in this file as well as twitter_archive_enhanced.  Drop "source" from cleaned_tweets.

24)  Remove the "lang" column.  It does not provide additional value to this study.  All tweets appear to be either english or jibberish.

25) Remove the truncated column as the only value is "False".

26) The text field contains two data elements (The rating response and the tweet URL.  The tweet URL should be separated.

#### Tidy Data Issues:

##### In the twitter_archive_enhanced file: 

1) We can see that doggo has the value of doggo if the animal is identified in that stage, otherwise it is populated with None.  Best approach is to move doggo, puppo, pupper, and floofer under a single variable, called development_stage.  This eliminates additional variables.

##### In the tweet-json.txt file:

2) tweets and twitter_archive_enhanced have the following duplicate column names: tweet_id, source, in_reply_to_status_id, and in_reply_to_user_id. Plan to delete keep tweet_id as it is common to all files and delete the in_reply_to_status_id and in_reply_to_user_id from the twitter_archive_enhanced file. tweets seems to have a fuller table and it makes sense it should go with that table.

3) Remove the geo, coordinates, place and contributors columns becaues they provide little to no data.

4) Remove the display_text_range column as it only provides the display text range

5) Remove the entities column as it does not provide any data that will be used in the analysis.

6) Drop is_quote_status as it does not add value to the analysis

7) The quoted_status_permalink does not appear to add value to the analysis.  

### Cleaning

We start by making copies of the original data files.

In [62]:
# create copies of the original datasets
cleaned_twitter_archive_enhanced = twitter_archive_enhanced.copy(deep=False)
cleaned_tweets = tweets.copy(deep=False)
cleaned_image_predictions = image_predictions.copy(deep=False)

### Define

There are a number of rows that are retweets. We will need to remove these. They can be indentified using "retweeted_status" variable.

### Code

In [63]:
# Identify number of rows of cleaned_tweets before cleaning
cleaned_tweets.shape[0]

2331

In [64]:
# strips out rows where retweeted_status is not null
cleaned_tweets = cleaned_tweets[cleaned_tweets.retweeted_status.isnull()]
cleaned_tweets = cleaned_tweets[cleaned_tweets.in_reply_to_status_id.isnull()]

### Test

In [65]:
# rechecks the number of rows after cleaning
cleaned_tweets.shape[0]

2091

In [66]:
# look at the structure of the cleaned_tweets dataset
cleaned_tweets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2091 entries, 0 to 2330
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype              
---  ------                         --------------  -----              
 0   created_at                     2091 non-null   datetime64[ns, UTC]
 1   id                             2091 non-null   int64              
 2   id_str                         2091 non-null   int64              
 3   full_text                      2091 non-null   object             
 4   truncated                      2091 non-null   bool               
 5   display_text_range             2091 non-null   object             
 6   entities                       2091 non-null   object             
 7   extended_entities              1964 non-null   object             
 8   source                         2091 non-null   object             
 9   in_reply_to_status_id          0 non-null      float64            
 10  in_reply_to_status_id_st

### Define

There are 181 rows that are retweets in the cleaned_twitter_archive_enhanced file.  We will need to remove these.  They can be indentified using "retweeted_status" variable.

### Code

In [67]:
# removes retweeted rows from the cleaned_twitter_enhanced archive file
cleaned_twitter_archive_enhanced = cleaned_twitter_archive_enhanced[cleaned_twitter_archive_enhanced.retweeted_status_id.isnull()]

### Test

Check to see that the 181 duplicate records were removed.

In [68]:
# verifies the duplicate rows were removed
cleaned_twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   tweet_id                    2175 non-null   int64  
 1   in_reply_to_status_id       78 non-null     float64
 2   in_reply_to_user_id         78 non-null     float64
 3   timestamp                   2175 non-null   object 
 4   source                      2175 non-null   object 
 5   text                        2175 non-null   object 
 6   retweeted_status_id         0 non-null      float64
 7   retweeted_status_user_id    0 non-null      float64
 8   retweeted_status_timestamp  0 non-null      object 
 9   expanded_urls               2117 non-null   object 
 10  rating_numerator            2175 non-null   int64  
 11  rating_denominator          2175 non-null   int64  
 12  name                        2175 non-null   object 
 13  doggo                       2175 

### Define

Change id in the cleaned_tweets file to tweet_id using .rename()

### Code

In [69]:
# renames id to tweet_id
cleaned_tweets = cleaned_tweets.rename(columns = {'id':'tweet_id'})

### Test

In [70]:
# verify id was renamed tweet_id
cleaned_tweets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2091 entries, 0 to 2330
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype              
---  ------                         --------------  -----              
 0   created_at                     2091 non-null   datetime64[ns, UTC]
 1   tweet_id                       2091 non-null   int64              
 2   id_str                         2091 non-null   int64              
 3   full_text                      2091 non-null   object             
 4   truncated                      2091 non-null   bool               
 5   display_text_range             2091 non-null   object             
 6   entities                       2091 non-null   object             
 7   extended_entities              1964 non-null   object             
 8   source                         2091 non-null   object             
 9   in_reply_to_status_id          0 non-null      float64            
 10  in_reply_to_status_id_st

### Define

Need to drop in_reply_to_status_id, in_reply_to_status_id_str, in_reply_to_user_id, in_reply_to_user_id_str, in_reply_to_screen_name, quoted_status_id, quoted_status_id_str, quoted_status,'possibly_sensitive,
possibly_sensitive_appealable, source, lang, truncated, display_text_range, entities, extended_entities, and is_quote_status


### Code

In [71]:
# drops fields from cleaned_tweets dataset
cleaned_tweets.drop(['in_reply_to_status_id','in_reply_to_status_id_str','in_reply_to_user_id',
                     'in_reply_to_user_id_str','in_reply_to_screen_name', 'quoted_status_id',
                     'quoted_status_id_str', 'quoted_status','possibly_sensitive',
                     'possibly_sensitive_appealable', 'source', 'lang', 'truncated', 
                     'display_text_range', 'entities', 'extended_entities', 'is_quote_status'], axis = 1, inplace = True)

### Define

Remove the geo, coordinates, place, contributors, and retweeted_status columns becaues they provide little to no data.

### Code

In [72]:
# drops additional fields from cleaned_tweets dataset
cleaned_tweets.drop(['geo','coordinates','place','contributors','retweeted_status'], axis = 1, inplace = True)

### Test

In [73]:
# verifies fields were dropped
cleaned_tweets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2091 entries, 0 to 2330
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype              
---  ------                   --------------  -----              
 0   created_at               2091 non-null   datetime64[ns, UTC]
 1   tweet_id                 2091 non-null   int64              
 2   id_str                   2091 non-null   int64              
 3   full_text                2091 non-null   object             
 4   user                     2091 non-null   object             
 5   retweet_count            2091 non-null   int64              
 6   favorite_count           2091 non-null   int64              
 7   favorited                2091 non-null   bool               
 8   retweeted                2091 non-null   bool               
 9   quoted_status_permalink  25 non-null     object             
dtypes: bool(2), datetime64[ns, UTC](1), int64(4), object(3)
memory usage: 151.1+ KB


### Define

Avoid errors by ensuring that retweet_count and favorite count are equal to 0 when the value is null.

### Code

In [74]:
# ensures retweet_count equal to zero if not greater than zero
cleaned_tweets.loc[(cleaned_tweets['retweet_count'] < 0) | (cleaned_tweets['retweet_count'].isnull()), 'retweet_count'] = 0

In [75]:
# ensures favorite_count equal to zero if not greater than zero
cleaned_tweets.loc[(cleaned_tweets['favorite_count'] < 0) | (cleaned_tweets['favorite_count'].isnull()), 'favorite_count'] = 0

### Test

In [76]:
# tests to see if null values remain
r_count_check = cleaned_tweets['retweet_count'].isnull()
f_count_check = cleaned_tweets['favorite_count'].isnull()

In [77]:
# displays results
r_count_check.unique(), f_count_check.unique()

(array([False]), array([False]))

### Define

Remove data for invalid dog names: "None", "an", 'the","very", "quite","one", "just", "actually","mad", "not", "officially", "infuriating", "unacceptable, "light", "his", "old", "all, "my", "such", "by, "this", "space", "life", and "a".

### Code

In [78]:
# creates a list of names to reset to "None"
names_to_remove = [ 'an', 'the','very', 'quite','one', 'just', 'actually','mad', 'not',
                   'officially', 'infuriating', 'unacceptable', 'light', 'his', 'old', 'all', 'my', 'such',
                   'by', 'this', 'space', 'life', 'a']

In [79]:
# provides a count of the names listed above in cleaned_twitter_archive_enhanced
namecount_before = (cleaned_twitter_archive_enhanced.name.isin(names_to_remove))

In [80]:
# displays the list of names
namecount_before.value_counts()

False    2074
True      101
Name: name, dtype: int64

In [81]:
# sets names in the dataset matching the list obove to "None"
cleaned_twitter_archive_enhanced = cleaned_twitter_archive_enhanced.reset_index(drop=True)
cleaned_twitter_archive_enhanced['name'] = cleaned_twitter_archive_enhanced.name.replace(names_to_remove, 'None')

### Test

In [82]:
# check to see if names in the list still appear in the dataset
namecount_after = (cleaned_twitter_archive_enhanced.name.isin(names_to_remove))
namecount_after.value_counts()

False    2175
Name: name, dtype: int64

### Define

Check non-numeric values in the retweet_count  and favorite_count numeric variables

### Code/Test

In [83]:
# look for the presence of integer values
valcheck = cleaned_tweets.applymap(lambda x: isinstance(x, (int)))

In [84]:
# validates the count of integers for retweet_count
valcheck['retweet_count'].value_counts()

True    2091
Name: retweet_count, dtype: int64

In [85]:
# validates the count of integers for favoriet_count
valcheck['favorite_count'].value_counts()

True    2091
Name: favorite_count, dtype: int64

### Define

Drop 'retweeted_status_id, retweeted_status_user_id, and retweeted_status_timestamp

### Code

In [86]:
# drop retweeted_status_id, retweeted_status_user_id, retweeeted_status_timestamp
cleaned_twitter_archive_enhanced.drop(['retweeted_status_id', 'retweeted_status_user_id', 'retweeted_status_timestamp'],
                                      axis = 1, inplace = True)

Test to see the retweeted_status_id, retweeted_status_user_id, and retweeted_status_timestamp are deleted.

### Test

In [87]:
# check to see that the fields were deleted
cleaned_twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2175 entries, 0 to 2174
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   tweet_id               2175 non-null   int64  
 1   in_reply_to_status_id  78 non-null     float64
 2   in_reply_to_user_id    78 non-null     float64
 3   timestamp              2175 non-null   object 
 4   source                 2175 non-null   object 
 5   text                   2175 non-null   object 
 6   expanded_urls          2117 non-null   object 
 7   rating_numerator       2175 non-null   int64  
 8   rating_denominator     2175 non-null   int64  
 9   name                   2175 non-null   object 
 10  doggo                  2175 non-null   object 
 11  floofer                2175 non-null   object 
 12  pupper                 2175 non-null   object 
 13  puppo                  2175 non-null   object 
dtypes: float64(2), int64(3), object(9)
memory usage: 238.0+ 

### Define

Use the rating_numerator and rating_denominator to calculate a column called rating

### Code

In [88]:
# calculates the rating field from rating_numerator and rating_denominator
cleaned_twitter_archive_enhanced['rating'] = (cleaned_twitter_archive_enhanced.rating_numerator/cleaned_twitter_archive_enhanced.rating_denominator)

### Test

In [89]:
# verify the rating field was created
cleaned_twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2175 entries, 0 to 2174
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   tweet_id               2175 non-null   int64  
 1   in_reply_to_status_id  78 non-null     float64
 2   in_reply_to_user_id    78 non-null     float64
 3   timestamp              2175 non-null   object 
 4   source                 2175 non-null   object 
 5   text                   2175 non-null   object 
 6   expanded_urls          2117 non-null   object 
 7   rating_numerator       2175 non-null   int64  
 8   rating_denominator     2175 non-null   int64  
 9   name                   2175 non-null   object 
 10  doggo                  2175 non-null   object 
 11  floofer                2175 non-null   object 
 12  pupper                 2175 non-null   object 
 13  puppo                  2175 non-null   object 
 14  rating                 2175 non-null   float64
dtypes: f

In [90]:
# check that rating field was calculated properly
print(cleaned_twitter_archive_enhanced[['rating_numerator', 'rating_denominator', 'rating']])

      rating_numerator  rating_denominator  rating
0                   13                  10     1.3
1                   13                  10     1.3
2                   12                  10     1.2
3                   13                  10     1.3
4                   12                  10     1.2
...                ...                 ...     ...
2170                 5                  10     0.5
2171                 6                  10     0.6
2172                 9                  10     0.9
2173                 7                  10     0.7
2174                 8                  10     0.8

[2175 rows x 3 columns]


### Define

In the twitter_archive_enhanced file, the tweet_id should be an object/string as it is not to be used in calculting statistics. It is meant to identify the tweet.  We will change it later.  For now, need to change it to an integer64 as it will affect Microsoft Excel when imported as a CSV (the scientific notation strips off the last few digits in Excel).

### Code

In [91]:
# change data type for tweet_id in the cleaned_twitter_archive_enhanced, cleaned_tweets and image_predictions datasets
cleaned_twitter_archive_enhanced['tweet_id'] = cleaned_twitter_archive_enhanced['tweet_id'].astype('int64')
cleaned_tweets['tweet_id'] = cleaned_tweets['tweet_id'].astype('int64')
cleaned_image_predictions['tweet_id'] = cleaned_image_predictions['tweet_id'].astype('int64')
# change timestamp data type to datetime
cleaned_twitter_archive_enhanced['timestamp'] = pd.to_datetime(cleaned_twitter_archive_enhanced['timestamp']) 

### Test

In [92]:
# verify the data structure
cleaned_twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2175 entries, 0 to 2174
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype              
---  ------                 --------------  -----              
 0   tweet_id               2175 non-null   int64              
 1   in_reply_to_status_id  78 non-null     float64            
 2   in_reply_to_user_id    78 non-null     float64            
 3   timestamp              2175 non-null   datetime64[ns, UTC]
 4   source                 2175 non-null   object             
 5   text                   2175 non-null   object             
 6   expanded_urls          2117 non-null   object             
 7   rating_numerator       2175 non-null   int64              
 8   rating_denominator     2175 non-null   int64              
 9   name                   2175 non-null   object             
 10  doggo                  2175 non-null   object             
 11  floofer                2175 non-null   object           

In the image_predictions 4) There are 543 images in the file that are not a picture of a dog. Need to remove these from the data.

### Define

Drop in_reply_to_status_id and in_reply_to_user_id

In [93]:
# drop in_reply_to_status_id and in_reply_to_user_id fields
cleaned_twitter_archive_enhanced.drop(['in_reply_to_status_id', 'in_reply_to_user_id'],
                                      axis = 1, inplace = True)

### Test

In [94]:
# verify fields are dropped
cleaned_twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2175 entries, 0 to 2174
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   int64              
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   text                2175 non-null   object             
 4   expanded_urls       2117 non-null   object             
 5   rating_numerator    2175 non-null   int64              
 6   rating_denominator  2175 non-null   int64              
 7   name                2175 non-null   object             
 8   doggo               2175 non-null   object             
 9   floofer             2175 non-null   object             
 10  pupper              2175 non-null   object             
 11  puppo               2175 non-null   object             
 12  rating              2175 non-null 

### Define

Remove image_predictions where the prediction1 is not a dog.

### Code

In [95]:
# identify the number of rows where prediction is not a dog, identify the number of rows were prediction is a dog
len(cleaned_image_predictions[cleaned_image_predictions.p1_dog == False]),  len(cleaned_image_predictions[cleaned_image_predictions.p1_dog == True])

(543, 1532)

In [96]:
# eliminate rows where image is not a dog
cleaned_image_predictions = cleaned_image_predictions[cleaned_image_predictions.p1_dog == True]

### Test

In [97]:
# identify the number of rows where prediction is not a dog, identify the number of rows were prediction is a dog
len(cleaned_image_predictions[cleaned_image_predictions.p1_dog == False]), len(cleaned_image_predictions[cleaned_image_predictions.p1_dog == True])

(0, 1532)

### Define

Dog names in column "pl" are not capitalized in all cases.  Capitalize them

### Code

In [98]:
# identify the number of rows where dog name is not capitalized
uncapped = sum(~cleaned_image_predictions.p1.str.istitle())
print('Total number of dog names that are not capitalized: ', uncapped)

Total number of dog names that are not capitalized:  1134


In [99]:
# capitalize the names of dogs
cleaned_image_predictions.p1 = cleaned_image_predictions.p1.str.title()


### Test

In [100]:
# identify the number of rows where dog name is not capitalized
uncapped = sum(~cleaned_image_predictions.p1.str.istitle())
print('Total number of dog names that are not capitalized: ', uncapped)

Total number of dog names that are not capitalized:  0


### Define

Convert twitter_archive_enhanced "timestamp  to datetime

### Code

In [101]:
# change timestamp to datetime
cleaned_twitter_archive_enhanced['timestamp'] = pd.to_datetime(cleaned_twitter_archive_enhanced['timestamp']) 

### Test

In [102]:
# verify timestamp changed to datetime
cleaned_twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2175 entries, 0 to 2174
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   int64              
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   text                2175 non-null   object             
 4   expanded_urls       2117 non-null   object             
 5   rating_numerator    2175 non-null   int64              
 6   rating_denominator  2175 non-null   int64              
 7   name                2175 non-null   object             
 8   doggo               2175 non-null   object             
 9   floofer             2175 non-null   object             
 10  pupper              2175 non-null   object             
 11  puppo               2175 non-null   object             
 12  rating              2175 non-null 

### Define

Clarify the purpose of the p1,p2,p3 variables by spelling out "prediction."

### Code

In [103]:
# rename all predictdion fields starting with letter p to prediction
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p1':'prediction1'})
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p1_conf':'prediction1_conf'})
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p1_dog':'prediction1_dog'})
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p2':'prediction2'})
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p2_conf':'prediction2_conf'})
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p2_dog':'prediction2_dog'})
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p3':'prediction3'})
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p3_conf':'prediction3_conf'})
cleaned_image_predictions = cleaned_image_predictions.rename(columns = {'p3_dog':'prediction3_dog'})

### Test

In [104]:
# verify changed to prediction
list(cleaned_image_predictions)

['tweet_id',
 'jpg_url',
 'img_num',
 'prediction1',
 'prediction1_conf',
 'prediction1_dog',
 'prediction2',
 'prediction2_conf',
 'prediction2_dog',
 'prediction3',
 'prediction3_conf',
 'prediction3_dog']

### Define

In the twitter_archive_enhanced file: 1) The pupper, doggo, floofer and puppo can be moved into a single column to classify the dog stage.

### Code

In [105]:
# move all development names under a single variable called development stage
cleaned_twitter_archive_enhanced['development_stage'] = cleaned_twitter_archive_enhanced[['doggo','floofer', 'pupper', 'puppo']].max(axis=1)

### Test

In [106]:
# verify stages moved into development stage using value_counts
cleaned_twitter_archive_enhanced['development_stage'].value_counts()

None       1831
pupper      234
doggo        75
puppo        25
floofer      10
Name: development_stage, dtype: int64

In [107]:
# check against original field count
cleaned_twitter_archive_enhanced['puppo'].value_counts()

None     2150
puppo      25
Name: puppo, dtype: int64

In [108]:
# check against original field count
cleaned_twitter_archive_enhanced['pupper'].value_counts()

None      1941
pupper     234
Name: pupper, dtype: int64

In [109]:
# check against original field count
cleaned_twitter_archive_enhanced['doggo'].value_counts()

None     2088
doggo      87
Name: doggo, dtype: int64

In [110]:
# check against original field count
cleaned_twitter_archive_enhanced['floofer'].value_counts()

None       2165
floofer      10
Name: floofer, dtype: int64

### Define

Drop the puppo, pupper, doggo, and floofer columns from cleaned_twitter_archive_enhanced

### Code

In [111]:
# drops the puppo, pupper, doggo, and floofer dog stage fields that are not needed
cleaned_twitter_archive_enhanced.drop(['puppo', 'pupper', 'doggo', 'floofer'], axis = 1, inplace = True)

### Test

In [112]:
#veriy fields were dropped
cleaned_twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2175 entries, 0 to 2174
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   int64              
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   text                2175 non-null   object             
 4   expanded_urls       2117 non-null   object             
 5   rating_numerator    2175 non-null   int64              
 6   rating_denominator  2175 non-null   int64              
 7   name                2175 non-null   object             
 8   rating              2175 non-null   float64            
 9   development_stage   2175 non-null   object             
dtypes: datetime64[ns, UTC](1), float64(1), int64(3), object(5)
memory usage: 170.0+ KB


### Define

There are a number of rows (781) where the puppy's "name" is equal to 'None'.  Try to find the names in the texts.  We will do this by:
* writing the tweet_id(s) and name(s) to a .csv file, 
* looking at the text in Excel, 
* saving the Excel file as a .csv, 
* reading the file into pandas as a .csv, and
* merging the file with the cleaned_archive_enhanced file


### Code

In [113]:
# identify rows where name is none and store in nameless dataset
nameless = cleaned_twitter_archive_enhanced[cleaned_twitter_archive_enhanced.name == 'None'].copy(deep=False)

In [114]:
nameless.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 781 entries, 5 to 2174
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            781 non-null    int64              
 1   timestamp           781 non-null    datetime64[ns, UTC]
 2   source              781 non-null    object             
 3   text                781 non-null    object             
 4   expanded_urls       723 non-null    object             
 5   rating_numerator    781 non-null    int64              
 6   rating_denominator  781 non-null    int64              
 7   name                781 non-null    object             
 8   rating              781 non-null    float64            
 9   development_stage   781 non-null    object             
dtypes: datetime64[ns, UTC](1), float64(1), int64(3), object(5)
memory usage: 67.1+ KB


In [115]:
# check list of names
list(nameless)

['tweet_id',
 'timestamp',
 'source',
 'text',
 'expanded_urls',
 'rating_numerator',
 'rating_denominator',
 'name',
 'rating',
 'development_stage']

Dropping unnecessary columns from the nameless dataset so it can be exported to Excel as a .csv file.

In [116]:
# drop fields that will not be written to nameless.csv
nameless.drop(['timestamp',
 'source',
 'expanded_urls',
 'rating_numerator',
 'rating_denominator',
 'development_stage'
 ], axis = 1, inplace = True)

In [117]:
# verify fields dropped
nameless.head()

tweet_id  \
5   891087950875897856   
7   890729181411237888   
12  889665388333682689   
21  887517139158093824   
23  887343217045368832   

                                                                                                   text  \
5   Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breath...   
7   When you watch your owner call another dog a good boy but then they turn back to you and say you...   
12  Here's a puppo that seems to be on the fence about something haha no but seriously someone help ...   
21  I've yet to rate a Venezuelan Hover Wiener. This is such an honor. 14/10 paw-inspiring af (IG: r...   
23  You may not have known you needed to see this today. 13/10 please enjoy (IG: emmylouroo) https:/...   

    name  rating  
5   None     1.3  
7   None     1.3  
12  None     1.3  
21  None     1.4  
23  None     1.3

Write the records with name = 'None' to "Nameless.csv"

In [118]:
# write nameless to nameless.csv
nameless.to_csv('Nameless.csv')

After reviewing the text in the Nameless.csv file using Excel, I created another column in the Nameless.csv file where I identified some additional names that were identified in the text string contained in the tweet.  Import the revised Nameless.csv file and join the new_name variable to the cleaned_twitter_archive_enhanced dataset.

In [119]:
# read in Nameless_newname.csv file conaining names that were found
nameless = pd.read_csv('Nameless_newname.csv')
nameless.head()

tweet_id  \
0  891087950875897856   
1  890729181411237888   
2  889665388333682689   
3  887517139158093824   
4  887343217045368832   

                                                                                                 text1  \
0  Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breath...   
1  When you watch your owner call another dog a good boy but then they turn back to you and say you...   
2  Here's a puppo that seems to be on the fence about something haha no but seriously someone help ...   
3  I've yet to rate a Venezuelan Hover Wiener. This is such an honor. 14/10 paw-inspiring af (IG: r...   
4  You may not have known you needed to see this today. 13/10 please enjoy (IG: emmylouroo) https:/...   

  new_name  
0      NaN  
1      NaN  
2      NaN  
3      NaN  
4      NaN

In [120]:
# view contents of nameless file
nameless.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851 entries, 0 to 850
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   tweet_id  851 non-null    int64 
 1   text1     851 non-null    object
 2   new_name  51 non-null     object
dtypes: int64(1), object(2)
memory usage: 20.1+ KB


In [121]:
# reset the index of cleaned_twitter_archive_enhanced
cleaned_twitter_archive_enhanced.reset_index(drop=True, inplace=True)

Merge the new_name column to the cleaned_twitter_archive_enhanced table, joining on tweet id.  This adds as many of the 51 names I identified as possible.

In [122]:
# merge the cleaned_twitter_arcive_enhanced file to nameless and call the new file cleaned_twitter_archive_enhanced_v1
cleaned_twitter_archive_enhanced_v1= pd.merge(cleaned_twitter_archive_enhanced, nameless, how='left', on='tweet_id')

### Test

In [123]:
# verify the merge was successful
cleaned_twitter_archive_enhanced_v1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2174
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   int64              
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   text                2175 non-null   object             
 4   expanded_urls       2117 non-null   object             
 5   rating_numerator    2175 non-null   int64              
 6   rating_denominator  2175 non-null   int64              
 7   name                2175 non-null   object             
 8   rating              2175 non-null   float64            
 9   development_stage   2175 non-null   object             
 10  text1               781 non-null    object             
 11  new_name            47 non-null     object             
dtypes: datetime64[ns, UTC](1), float64

In [124]:
# create a copy of the merged file
cleaned_twitter_archive_enhanced_v2 = cleaned_twitter_archive_enhanced_v1

In [125]:
# test to ensure new_name field copied to name when new_name is not null
cleaned_twitter_archive_enhanced_v2.loc[cleaned_twitter_archive_enhanced_v2.new_name.notnull(), 'name'] = cleaned_twitter_archive_enhanced_v2.new_name

In [126]:
# check to see that name was updated
cleaned_twitter_archive_enhanced_v2.query('name == "Burke and Dexter"')

tweet_id                 timestamp  \
442  808106460588765185 2016-12-12 00:29:28+00:00   

                                                                                 source  \
442  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                    text  \
442  Here we have Burke (pupper) and Dexter (doggo). Pupper wants to be exactly like doggo. Both 12/1...   

                                                       expanded_urls  \
442  https://twitter.com/dog_rates/status/808106460588765185/photo/1   

     rating_numerator  rating_denominator              name  rating  \
442                12                  10  Burke and Dexter     1.2   

    development_stage  \
442            pupper   

                                                                                                   text1  \
442  Here we have Burke (pupper) and Dexter (doggo). Pupper wants to be exactly like doggo. Both 12/1...   

             new_name  
442  Burke and Dexter

In [127]:
# check total count of rows in new dataset 
cleaned_twitter_archive_enhanced_v2['name'].value_counts()

None                  734
Charlie                12
Lucy                   11
Oliver                 11
Cooper                 11
Tucker                  9
Penny                   9
Lola                    8
Winston                 8
Sadie                   8
Toby                    8
Daisy                   7
Oscar                   6
Koda                    6
Stanley                 6
Bo                      6
Jax                     6
Bailey                  6
Bella                   6
Scout                   5
Buddy                   5
Boomer                  5
Louis                   5
Bentley                 5
Leo                     5
Rusty                   5
Chester                 5
Milo                    5
Dave                    5
Zoey                    5
Winnie                  4
Jack                    4
Chip                    4
Bear                    4
Jerry                   4
Derek                   4
Alfie                   4
Brody                   4
Larry       

In [128]:
# check contents of new dataset
cleaned_twitter_archive_enhanced_v1.head(5)

tweet_id                 timestamp  \
0  892420643555336193 2017-08-01 16:23:56+00:00   
1  892177421306343426 2017-08-01 00:17:27+00:00   
2  891815181378084864 2017-07-31 00:18:03+00:00   
3  891689557279858688 2017-07-30 15:58:51+00:00   
4  891327558926688256 2017-07-29 16:00:24+00:00   

                                                                               source  \
0  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
1  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
2  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
3  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   
4  <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>   

                                                                                                  text  \
0  This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t....   
1  This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available fo...   
2  This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know w...   
3  This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us https://t.co/tD3...   
4  This is Franklin. He would like you to stop calling him "cute." He is a very fierce shark and sh...   

                                                                                         expanded_urls  \
0                                      https://twitter.com/dog_rates/status/892420643555336193/photo/1   
1                                      https://twitter.com/dog_rates/status/892177421306343426/photo/1   
2                                      https://twitter.com/dog_rates/status/891815181378084864/photo/1   
3                                      https://twitter.com/dog_rates/status/891689557279858688/photo/1   
4  https://twitter.com/dog_rates/status/891327558926688256/photo/1,https://twitter.com/dog_rates/st...   

   rating_numerator  rating_denominator      name  rating development_stage  \
0                13                  10   Phineas     1.3              None   
1                13                  10     Tilly     1.3              None   
2                12                  10    Archie     1.2              None   
3                13                  10     Darla     1.3              None   
4                12                  10  Franklin     1.2              None   

  text1 new_name  
0   NaN      NaN  
1   NaN      NaN  
2   NaN      NaN  
3   NaN      NaN  
4   NaN      NaN

In [129]:
name_counter = cleaned_twitter_archive_enhanced_v2['name'].value_counts()
name_counter.head()

None       734
Charlie     12
Lucy        11
Oliver      11
Cooper      11
Name: name, dtype: int64

The total number of name = None has been reduced from 745 to 734.

### Define

The text field contains two data elements (The rating response and the tweet URL.  The tweet URL should be separated.

### Code

In [130]:
# split text into additional columns
cleaned_twitter_archive_enhanced_v1['text1'] = cleaned_twitter_archive_enhanced_v1['text'].str.split('https:', expand=True)

In [131]:
# split text into additional columns
cleaned_twitter_archive_enhanced_v1['twitter_URLs'] = cleaned_twitter_archive_enhanced_v1.text.apply(lambda x : x.strip().split(' ')[-1])

### Test

In [132]:
# verify split worked
cleaned_twitter_archive_enhanced_v1['text1']

0                    This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 
1       This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available fo...
2       This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know w...
3                          This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us 
4       This is Franklin. He would like you to stop calling him "cute." He is a very fierce shark and sh...
                                                       ...                                                 
2170      Here we have a 1949 1st generation vulpix. Enjoys sweat tea and Fox News. Cannot be phased. 5/10 
2171    This is a purebred Piers Morgan. Loves to Netflix and chill. Always looks like he forgot to unpl...
2172    Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would...
2173    This is a western br

In [133]:
# verify split worked
cleaned_twitter_archive_enhanced_v1['twitter_URLs']

0       https://t.co/MgUWQ76dJU
1       https://t.co/0Xxu71qeIV
2       https://t.co/wUnZnhtVJB
3       https://t.co/tD36da7qLQ
4       https://t.co/AtUZn91f7f
                 ...           
2170    https://t.co/4B7cOc1EDq
2171    https://t.co/DWnyCjf2mx
2172    https://t.co/y671yMhoiR
2173    https://t.co/r7mOb2m0UI
2174    https://t.co/BLDqew2Ijj
Name: twitter_URLs, Length: 2175, dtype: object

In [134]:
# verify split worked
cleaned_twitter_archive_enhanced_v1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2174
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   int64              
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   text                2175 non-null   object             
 4   expanded_urls       2117 non-null   object             
 5   rating_numerator    2175 non-null   int64              
 6   rating_denominator  2175 non-null   int64              
 7   name                2175 non-null   object             
 8   rating              2175 non-null   float64            
 9   development_stage   2175 non-null   object             
 10  text1               2175 non-null   object             
 11  new_name            47 non-null     object             
 12  twitter_URLs        2175 non-null 

In [135]:
# drop new_name and text
cleaned_twitter_archive_enhanced_v1 = cleaned_twitter_archive_enhanced_v2
cleaned_twitter_archive_enhanced_v1.drop(['text', 'new_name'], axis = 1, inplace = True)
# reset the index
cleaned_twitter_archive_enhanced_v1.reset_index(drop=True, inplace=True)

### Define

Rename text1 as text

### Code

In [136]:
# rename text1 column to text
cleaned_twitter_archive_enhanced_v1 = cleaned_twitter_archive_enhanced_v1.rename(columns = {'text1':'text'})

### Test

In [137]:
# verify the structure of text
cleaned_twitter_archive_enhanced_v1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2175 entries, 0 to 2174
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   int64              
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   expanded_urls       2117 non-null   object             
 4   rating_numerator    2175 non-null   int64              
 5   rating_denominator  2175 non-null   int64              
 6   name                2175 non-null   object             
 7   rating              2175 non-null   float64            
 8   development_stage   2175 non-null   object             
 9   text                2175 non-null   object             
 10  twitter_URLs        2175 non-null   object             
dtypes: datetime64[ns, UTC](1), float64(1), int64(3), object(6)
memory usage: 187.0+ KB


### Define

Ensure that retweet_count and favorite_count blank values are set to null after the merge.

### Code

In [138]:
# ensure retweet_count null values are set to zero
cleaned_tweets.loc[~(cleaned_tweets['retweet_count'] > 0)] = 0

In [139]:
# ensure favorite_count null values are set to zero
cleaned_tweets.loc[~(cleaned_tweets['favorite_count'] > 0)] = 0

In [140]:
# reset the index
cleaned_twitter_archive_enhanced_v1.reset_index(drop=True, inplace=True)
cleaned_tweets.reset_index(drop=True, inplace=True)

### Test

In [141]:
# check to see if any null values exist
r_count_check['retweet_count'] = cleaned_tweets['retweet_count'].isnull()
f_count_check['favorite_count'] = cleaned_tweets['favorite_count'].isnull()

In [142]:
r_count_check['retweet_count'].unique(), f_count_check['favorite_count'].unique()

(array([False]), array([False]))

### Define

Drop the quoted_status_permalink field

### Code

In [143]:
# drop the quoted_status_permalink field
cleaned_tweets.drop(['quoted_status_permalink'], axis = 1, inplace = True)

### Test

In [144]:
# verify fields were dropped
cleaned_tweets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2091 entries, 0 to 2090
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   created_at      2091 non-null   object
 1   tweet_id        2091 non-null   int64 
 2   id_str          2091 non-null   int64 
 3   full_text       2091 non-null   object
 4   user            2091 non-null   object
 5   retweet_count   2091 non-null   int64 
 6   favorite_count  2091 non-null   int64 
 7   favorited       2091 non-null   object
 8   retweeted       2091 non-null   object
dtypes: int64(4), object(5)
memory usage: 147.1+ KB


### Define

Using merge, join the cleaned_twitter_archive_enhanced_v1 and the cleaned_image_predictions files together, with cleaned_twitter_archive_enhanced as the primary and using tweet_id as the primary key

### Code

In [145]:
# merge the cleaned_twitter_archive_enhanced_v1 feld with cleaned_image_predictions
cleaned_twitter_archive_and_images = pd.merge(cleaned_twitter_archive_enhanced_v1, 
                                              cleaned_image_predictions, how='left', on='tweet_id', copy = False)

### Test

In [146]:
# verify the merge was successful
cleaned_twitter_archive_and_images.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2174
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   int64              
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   expanded_urls       2117 non-null   object             
 4   rating_numerator    2175 non-null   int64              
 5   rating_denominator  2175 non-null   int64              
 6   name                2175 non-null   object             
 7   rating              2175 non-null   float64            
 8   development_stage   2175 non-null   object             
 9   text                2175 non-null   object             
 10  twitter_URLs        2175 non-null   object             
 11  jpg_url             1477 non-null   object             
 12  img_num             1477 non-null 

In [147]:
# verify the value counts for development stages
cleaned_twitter_archive_and_images['development_stage'].value_counts()

None       1831
pupper      234
doggo        75
puppo        25
floofer      10
Name: development_stage, dtype: int64

### Define

Using merge, join the cleaned_twitter_archive_and_images and the cleaned_tweets files together, with cleaned_twitter_archive_and_images as the primary.

### Code

In [148]:
# reset the indexes for cleaned_tweets and cleaned_twitter_archive_and_images
cleaned_tweets.reset_index(drop=True, inplace=True)
cleaned_twitter_archive_and_images.reset_index(drop=True, inplace=True)

In [149]:
# merge  cleaned_tweets and cleaned_twitter_archive_and_images
twitter_archive_master = pd.merge(cleaned_twitter_archive_and_images, cleaned_tweets, how='left', on='tweet_id', copy =False)

### Test

In [150]:
# verify the merge was successful
twitter_archive_master.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2174
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   int64              
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   expanded_urls       2117 non-null   object             
 4   rating_numerator    2175 non-null   int64              
 5   rating_denominator  2175 non-null   int64              
 6   name                2175 non-null   object             
 7   rating              2175 non-null   float64            
 8   development_stage   2175 non-null   object             
 9   text                2175 non-null   object             
 10  twitter_URLs        2175 non-null   object             
 11  jpg_url             1477 non-null   object             
 12  img_num             1477 non-null 

### Define

Ensure that retweet_count and favorite_count do not have any null values as a result of the merge.

### Code

In [151]:
# ensure that null values were set to zero 
twitter_archive_master.loc[(twitter_archive_master['retweet_count'] < 0) | (twitter_archive_master['retweet_count'].isnull()), 'retweet_count'] = 0
twitter_archive_master.loc[(twitter_archive_master['favorite_count'] < 0) | (twitter_archive_master['favorite_count'].isnull()), 'favorite_count'] = 0

In [152]:
# change float to integer for retweet_count 
twitter_archive_master['retweet_count'] = twitter_archive_master['retweet_count'].astype('int64', errors='raise')


In [153]:
# change float to integer for favorite_count
twitter_archive_master['favorite_count'] = twitter_archive_master['favorite_count'].astype('int64', errors='raise')

### Test

In [154]:
# look for null values
r_count_check['retweet_count'] = twitter_archive_master['retweet_count'].isnull()
f_count_check['favorite_count'] = twitter_archive_master['favorite_count'].isnull()

In [155]:
# verify null values are not present
r_count_check['retweet_count'].unique(), f_count_check['favorite_count'].unique()

(array([False]), array([False]))

### Define

Convert tweet_id to type = string

### Code

In [156]:
# change tweet_id to string
twitter_archive_master['tweet_id'] = twitter_archive_master.tweet_id.astype(str)


### Test

In [157]:
# verify tweet_id changed to string
twitter_archive_master.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2174
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype              
---  ------              --------------  -----              
 0   tweet_id            2175 non-null   object             
 1   timestamp           2175 non-null   datetime64[ns, UTC]
 2   source              2175 non-null   object             
 3   expanded_urls       2117 non-null   object             
 4   rating_numerator    2175 non-null   int64              
 5   rating_denominator  2175 non-null   int64              
 6   name                2175 non-null   object             
 7   rating              2175 non-null   float64            
 8   development_stage   2175 non-null   object             
 9   text                2175 non-null   object             
 10  twitter_URLs        2175 non-null   object             
 11  jpg_url             1477 non-null   object             
 12  img_num             1477 non-null 

### Save Master File

Save twitter_archive_master.csv to local drive

In [158]:
# save twitter_archive_master to .csv file
twitter_archive_master.to_csv('twitter_archive_master.csv', index = False, encoding = 'utf-8')

### Analysis is located in wrangle_report.inpyb